/** Common dosage forms, with the stock unit each is usually counted in. */
export const DOSAGE_FORMS: Array<{ form: string; unit: string }> = [
  { form: 'Tablet', unit: 'tablet' },
  { form: 'Capsule', unit: 'capsule' },
  { form: 'Syrup', unit: 'bottle' },
  { form: 'Suspension', unit: 'bottle' },
  { form: 'Oral solution', unit: 'bottle' },
  { form: 'Oral drops', unit: 'bottle' },
  { form: 'Powder for oral suspension', unit: 'bottle' },
  { form: 'Sachet / granules', unit: 'sachet' },
  { form: 'Lozenge', unit: 'lozenge' },
  { form: 'Injection', unit: 'vial' },
  { form: 'Injection (ampoule)', unit: 'ampoule' },
  { form: 'IV infusion / fluid', unit: 'bag' },
  { form: 'Cream', unit: 'tube' },
  { form: 'Ointment', unit: 'tube' },
  { form: 'Gel', unit: 'tube' },
  { form: 'Lotion', unit: 'bottle' },
  { form: 'Eye drops', unit: 'bottle' },
  { form: 'Eye ointment', unit: 'tube' },
  { form: 'Ear drops', unit: 'bottle' },
  { form: 'Nasal drops / spray', unit: 'bottle' },
  { form: 'Inhaler', unit: 'inhaler' },
  { form: 'Nebuliser solution', unit: 'nebule' },
  { form: 'Suppository', unit: 'suppository' },
  { form: 'Pessary', unit: 'pessary' },
  { form: 'Transdermal patch', unit: 'patch' },
  { form: 'Mouthwash', unit: 'bottle' },
  { form: 'Implant', unit: 'implant' },
  { form: 'Vaccine', unit: 'vial' },
];
export const STOCK_UNITS = ['unit', 'tablet', 'capsule', 'bottle', 'vial', 'ampoule', 'bag', 'tube', 'sachet', 'inhaler', 'nebule', 'suppository', 'pessary', 'patch', 'lozenge', 'implant', 'box', 'pack', 'strip', 'piece', 'pair', 'roll', 'kit', 'litre', 'ml', 'g', 'kg'];
