/**
 * Starter diagnosis list for new facilities: common reasons for admission in Kenyan facilities.
 * Names only: ICD codes are deliberately not pre-filled, because a wrong code would flow into
 * records and claims. Facilities add the codes they use (or import them) in Admin → Diagnoses.
 */
export const DEFAULT_DIAGNOSES: Array<{ name: string; category: string; synonyms?: string[]; notifiable?: boolean }> = [
  { name: 'Severe malaria', category: 'Infections', synonyms: ['complicated malaria'] },
  { name: 'Uncomplicated malaria', category: 'Infections' },
  { name: 'Pneumonia', category: 'Respiratory' },
  { name: 'Severe pneumonia', category: 'Respiratory' },
  { name: 'Acute gastroenteritis with dehydration', category: 'Gastrointestinal', synonyms: ['AGE', 'diarrhoea and vomiting'] },
  { name: 'Sepsis', category: 'Infections' },
  { name: 'Neonatal sepsis', category: 'Neonatal' },
  { name: 'Neonatal jaundice', category: 'Neonatal' },
  { name: 'Prematurity / low birth weight', category: 'Neonatal' },
  { name: 'Birth asphyxia', category: 'Neonatal' },
  { name: 'Severe acute malnutrition', category: 'Nutrition', synonyms: ['SAM'] },
  { name: 'Severe anaemia', category: 'Blood' },
  { name: 'Typhoid fever', category: 'Infections', notifiable: true },
  { name: 'Urinary tract infection', category: 'Renal / urinary', synonyms: ['UTI'] },
  { name: 'Acute pyelonephritis', category: 'Renal / urinary' },
  { name: 'Meningitis', category: 'Infections', notifiable: true },
  { name: 'Pulmonary tuberculosis', category: 'Infections', synonyms: ['PTB', 'TB'], notifiable: true },
  { name: 'HIV-related illness', category: 'Infections' },
  { name: 'Cholera', category: 'Infections', notifiable: true },
  { name: 'Acute asthma exacerbation', category: 'Respiratory' },
  { name: 'COPD exacerbation', category: 'Respiratory' },
  { name: 'Hypertensive emergency', category: 'Cardiovascular', synonyms: ['hypertensive crisis'] },
  { name: 'Stroke', category: 'Cardiovascular', synonyms: ['CVA', 'cerebrovascular accident'] },
  { name: 'Congestive heart failure', category: 'Cardiovascular', synonyms: ['CCF', 'CHF'] },
  { name: 'Diabetic ketoacidosis', category: 'Endocrine', synonyms: ['DKA'] },
  { name: 'Uncontrolled diabetes mellitus', category: 'Endocrine' },
  { name: 'Hypoglycaemia', category: 'Endocrine' },
  { name: 'Acute kidney injury', category: 'Renal / urinary', synonyms: ['AKI'] },
  { name: 'Chronic kidney disease', category: 'Renal / urinary', synonyms: ['CKD'] },
  { name: 'Upper gastrointestinal bleeding', category: 'Gastrointestinal', synonyms: ['UGIB', 'haematemesis'] },
  { name: 'Peptic ulcer disease', category: 'Gastrointestinal', synonyms: ['PUD'] },
  { name: 'Acute appendicitis', category: 'Surgical' },
  { name: 'Intestinal obstruction', category: 'Surgical' },
  { name: 'Cellulitis / abscess', category: 'Skin and soft tissue' },
  { name: 'Burns', category: 'Injuries' },
  { name: 'Head injury', category: 'Injuries' },
  { name: 'Fracture (specify site)', category: 'Injuries' },
  { name: 'Road traffic injuries', category: 'Injuries', synonyms: ['RTA', 'RTI'] },
  { name: 'Snake bite', category: 'Injuries' },
  { name: 'Poisoning', category: 'Injuries' },
  { name: 'Seizures / status epilepticus', category: 'Neurological' },
  { name: 'Pre-eclampsia', category: 'Obstetric' },
  { name: 'Eclampsia', category: 'Obstetric' },
  { name: 'Labour at term', category: 'Obstetric' },
  { name: 'Preterm labour', category: 'Obstetric' },
  { name: 'Antepartum haemorrhage', category: 'Obstetric', synonyms: ['APH'] },
  { name: 'Postpartum haemorrhage', category: 'Obstetric', synonyms: ['PPH'] },
  { name: 'Incomplete abortion', category: 'Obstetric', synonyms: ['post-abortion care'] },
  { name: 'Ectopic pregnancy', category: 'Obstetric' },
  { name: 'Hyperemesis gravidarum', category: 'Obstetric' },
  { name: 'Febrile illness for investigation', category: 'General' },
  { name: 'Admitted for observation', category: 'General' },
];
