// GENERATED by scripts/gen-openapi-routes.mjs — do not edit by hand.
import type { RouteDoc } from './openapi';

export const generatedRoutes: Record<string, Record<string, RouteDoc>> = {
  "/api/v1/admin/audit": {
    "get": {
      "summary": "Get admin audit",
      "tag": "Admin",
      "permission": "admin.audit"
    }
  },
  "/api/v1/admin/branding": {
    "get": {
      "summary": "Get admin branding",
      "tag": "Admin",
      "permission": "admin.settings"
    },
    "put": {
      "summary": "Replace admin branding",
      "tag": "Admin",
      "permission": "admin.settings"
    }
  },
  "/api/v1/admin/branding/logo": {
    "put": {
      "summary": "Replace admin branding logo",
      "tag": "Admin",
      "permission": "admin.settings"
    },
    "delete": {
      "summary": "Delete admin branding logo",
      "tag": "Admin",
      "permission": "admin.settings"
    }
  },
  "/api/v1/admin/integrations": {
    "get": {
      "summary": "Get admin integrations",
      "tag": "Admin",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/admin/integrations/{provider}": {
    "put": {
      "summary": "Replace admin integrations",
      "tag": "Admin",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/admin/integrations/{provider}/test": {
    "post": {
      "summary": "Create/perform admin integrations test",
      "tag": "Admin",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/admin/security/google-login": {
    "put": {
      "summary": "Replace admin security google login",
      "tag": "Admin",
      "permission": "admin.settings"
    },
    "get": {
      "summary": "Get admin security google login",
      "tag": "Admin",
      "permission": "admin.settings"
    }
  },
  "/api/v1/admin/security/mfa-policy": {
    "get": {
      "summary": "Get admin security mfa policy",
      "tag": "Admin",
      "permission": "admin.settings"
    },
    "put": {
      "summary": "Replace admin security mfa policy",
      "tag": "Admin",
      "permission": "admin.settings"
    }
  },
  "/api/v1/admin/settings": {
    "get": {
      "summary": "Get admin settings",
      "tag": "Admin",
      "permission": "admin.settings"
    }
  },
  "/api/v1/admin/settings/{key}": {
    "put": {
      "summary": "Replace admin settings",
      "tag": "Admin",
      "permission": "admin.settings"
    }
  },
  "/api/v1/admin/support-access": {
    "get": {
      "summary": "Get admin support access",
      "tag": "Admin",
      "permission": "admin.support_access"
    }
  },
  "/api/v1/admin/support-access/{id}/{decision}": {
    "post": {
      "summary": "Create/perform admin support access",
      "tag": "Admin",
      "permission": "admin.support_access"
    }
  },
  "/api/v1/admin/system-health/integrations": {
    "get": {
      "summary": "Get admin system health integrations",
      "tag": "Admin",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/announcements": {
    "get": {
      "summary": "Get announcements",
      "tag": "Announcements"
    }
  },
  "/api/v1/announcements/seen": {
    "post": {
      "summary": "Create/perform announcements seen",
      "tag": "Announcements"
    }
  },
  "/api/v1/announcements/unread-count": {
    "get": {
      "summary": "Get announcements unread count",
      "tag": "Announcements"
    }
  },
  "/api/v1/appointments": {
    "get": {
      "summary": "Get appointments",
      "tag": "Appointments",
      "permission": "appointments.view"
    },
    "post": {
      "summary": "Create/perform appointments",
      "tag": "Appointments",
      "permission": "appointments.manage"
    }
  },
  "/api/v1/appointments/{id}": {
    "patch": {
      "summary": "Update appointments",
      "tag": "Appointments",
      "permission": "appointments.manage"
    }
  },
  "/api/v1/appointments/course": {
    "post": {
      "summary": "Create/perform appointments course",
      "tag": "Appointments",
      "permission": "appointments.manage"
    }
  },
  "/api/v1/appointments/export": {
    "get": {
      "summary": "Get appointments export",
      "tag": "Appointments",
      "permission": "appointments.view"
    }
  },
  "/api/v1/appointments/providers": {
    "get": {
      "summary": "Get appointments providers",
      "tag": "Appointments",
      "permission": "appointments.view"
    }
  },
  "/api/v1/appointments/services": {
    "get": {
      "summary": "Get appointments services",
      "tag": "Appointments",
      "permission": "appointments.view"
    }
  },
  "/api/v1/appointments/slots": {
    "get": {
      "summary": "Get appointments slots",
      "tag": "Appointments",
      "permission": "appointments.view"
    }
  },
  "/api/v1/auth/activity": {
    "get": {
      "summary": "Get auth activity",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/branding/logo": {
    "get": {
      "summary": "Get auth branding logo",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/change-password": {
    "post": {
      "summary": "Create/perform auth change password",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/context": {
    "get": {
      "summary": "Get auth context",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/find-facility": {
    "post": {
      "summary": "Create/perform auth find facility",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/find-facility/select": {
    "post": {
      "summary": "Create/perform auth find facility select",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/forgot-password": {
    "post": {
      "summary": "Create/perform auth forgot password",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/handoff": {
    "post": {
      "summary": "Create/perform auth handoff",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/letterhead": {
    "get": {
      "summary": "Get auth letterhead",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/login": {
    "post": {
      "summary": "Create/perform auth login",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/logout": {
    "post": {
      "summary": "Create/perform auth logout",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/me": {
    "get": {
      "summary": "Get auth me",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/profile": {
    "get": {
      "summary": "Get auth profile",
      "tag": "Auth"
    },
    "patch": {
      "summary": "Update auth profile",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/refresh": {
    "post": {
      "summary": "Create/perform auth refresh",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/reset-password": {
    "post": {
      "summary": "Create/perform auth reset password",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/sessions": {
    "get": {
      "summary": "Get auth sessions",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/sessions/{id}/revoke": {
    "post": {
      "summary": "Create/perform auth sessions revoke",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/sessions/revoke-others": {
    "post": {
      "summary": "Create/perform auth sessions revoke others",
      "tag": "Auth"
    }
  },
  "/api/v1/billing/invoices": {
    "get": {
      "summary": "Get billing invoices",
      "tag": "Billing",
      "permission": "billing.view"
    },
    "post": {
      "summary": "Create/perform billing invoices",
      "tag": "Billing",
      "permission": "billing.create"
    }
  },
  "/api/v1/billing/invoices/{id}": {
    "get": {
      "summary": "Get billing invoices",
      "tag": "Billing",
      "permission": "billing.view"
    }
  },
  "/api/v1/billing/invoices/{id}/adjustments": {
    "post": {
      "summary": "Create/perform billing invoices adjustments",
      "tag": "Billing",
      "permission": "billing.waive"
    }
  },
  "/api/v1/billing/invoices/{id}/credit-notes": {
    "post": {
      "summary": "Create/perform billing invoices credit notes",
      "tag": "Billing",
      "permission": "billing.refund"
    }
  },
  "/api/v1/billing/invoices/{id}/issue": {
    "post": {
      "summary": "Create/perform billing invoices issue",
      "tag": "Billing",
      "permission": "billing.create"
    }
  },
  "/api/v1/billing/invoices/{id}/lines": {
    "post": {
      "summary": "Create/perform billing invoices lines",
      "tag": "Billing",
      "permission": "billing.create"
    }
  },
  "/api/v1/billing/invoices/{id}/lines/{lineId}/reprice": {
    "post": {
      "summary": "Create/perform billing invoices lines reprice",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/invoices/{id}/lines/{lineId}/void": {
    "post": {
      "summary": "Create/perform billing invoices lines void",
      "tag": "Billing",
      "permission": "billing.waive"
    }
  },
  "/api/v1/billing/invoices/{id}/void": {
    "post": {
      "summary": "Create/perform billing invoices void",
      "tag": "Billing",
      "permission": "billing.refund"
    }
  },
  "/api/v1/billing/payments": {
    "post": {
      "summary": "Create/perform billing payments",
      "tag": "Billing",
      "permission": "billing.create"
    },
    "get": {
      "summary": "Get billing payments",
      "tag": "Billing",
      "permission": "billing.view"
    }
  },
  "/api/v1/billing/payments/{id}/allocate": {
    "post": {
      "summary": "Create/perform billing payments allocate",
      "tag": "Billing",
      "permission": "billing.create"
    }
  },
  "/api/v1/billing/payments/{id}/receipt": {
    "get": {
      "summary": "Get billing payments receipt",
      "tag": "Billing",
      "permission": "billing.view"
    }
  },
  "/api/v1/billing/payments/{id}/refund": {
    "post": {
      "summary": "Create/perform billing payments refund",
      "tag": "Billing",
      "permission": "billing.refund"
    }
  },
  "/api/v1/billing/schemes": {
    "get": {
      "summary": "Get billing schemes",
      "tag": "Billing",
      "permission": "billing.view | queue.manage | insurance.view | billing.prices"
    },
    "post": {
      "summary": "Create/perform billing schemes",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/schemes/{id}": {
    "patch": {
      "summary": "Update billing schemes",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/schemes/{id}/utilisation": {
    "get": {
      "summary": "Get billing schemes utilisation",
      "tag": "Billing",
      "permission": "billing.view | insurance.view | reports.view"
    }
  },
  "/api/v1/billing/services": {
    "get": {
      "summary": "Get billing services",
      "tag": "Billing",
      "permission": "billing.view"
    },
    "post": {
      "summary": "Create/perform billing services",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/services/{id}": {
    "patch": {
      "summary": "Update billing services",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/services/import": {
    "post": {
      "summary": "Create/perform billing services import",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/services/import-template": {
    "get": {
      "summary": "Get billing services import template",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/summary": {
    "get": {
      "summary": "Get billing summary",
      "tag": "Billing",
      "permission": "billing.view"
    }
  },
  "/api/v1/blog/images/{id}": {
    "get": {
      "summary": "Get blog images",
      "tag": "Blog"
    }
  },
  "/api/v1/blog/posts": {
    "get": {
      "summary": "Get blog posts",
      "tag": "Blog"
    }
  },
  "/api/v1/blog/posts/{slug}": {
    "get": {
      "summary": "Get blog posts",
      "tag": "Blog"
    }
  },
  "/api/v1/branches": {
    "get": {
      "summary": "Get branches",
      "tag": "Branches"
    },
    "post": {
      "summary": "Create/perform branches",
      "tag": "Branches",
      "permission": "admin.branches"
    }
  },
  "/api/v1/branches/{id}": {
    "get": {
      "summary": "Get branches",
      "tag": "Branches"
    },
    "patch": {
      "summary": "Update branches",
      "tag": "Branches",
      "permission": "admin.branches"
    }
  },
  "/api/v1/branches/{id}/staff": {
    "put": {
      "summary": "Replace branches staff",
      "tag": "Branches",
      "permission": "admin.users"
    }
  },
  "/api/v1/consultations": {
    "post": {
      "summary": "Create/perform consultations",
      "tag": "Consultations",
      "permission": "consultation.create"
    },
    "get": {
      "summary": "Get consultations",
      "tag": "Consultations",
      "permission": "consultation.view"
    }
  },
  "/api/v1/consultations/{id}": {
    "get": {
      "summary": "Get consultations",
      "tag": "Consultations",
      "permission": "consultation.view"
    },
    "patch": {
      "summary": "Update consultations",
      "tag": "Consultations",
      "permission": "consultation.create"
    }
  },
  "/api/v1/consultations/{id}/addenda": {
    "post": {
      "summary": "Create/perform consultations addenda",
      "tag": "Consultations",
      "permission": "consultation.create"
    }
  },
  "/api/v1/consultations/{id}/finalize": {
    "post": {
      "summary": "Create/perform consultations finalize",
      "tag": "Consultations",
      "permission": "consultation.finalize"
    }
  },
  "/api/v1/contact": {
    "post": {
      "summary": "Create/perform contact",
      "tag": "Contact"
    }
  },
  "/api/v1/dashboard": {
    "get": {
      "summary": "Get dashboard",
      "tag": "Dashboard"
    }
  },
  "/api/v1/dental/patients/{id}/chart": {
    "get": {
      "summary": "Get dental patients chart",
      "tag": "Dental",
      "permission": "dental.view"
    },
    "put": {
      "summary": "Replace dental patients chart",
      "tag": "Dental",
      "permission": "dental.manage"
    }
  },
  "/api/v1/dental/visits": {
    "post": {
      "summary": "Create/perform dental visits",
      "tag": "Dental",
      "permission": "dental.manage"
    }
  },
  "/api/v1/dental/visits/{id}/plan/{itemId}/{action}": {
    "post": {
      "summary": "Create/perform dental visits plan",
      "tag": "Dental",
      "permission": "dental.manage"
    }
  },
  "/api/v1/dha/identification-types": {
    "get": {
      "summary": "Get dha identification types",
      "tag": "DHA",
      "permission": "dha.registry"
    }
  },
  "/api/v1/dha/registries/facilities": {
    "get": {
      "summary": "Get dha registries facilities",
      "tag": "DHA",
      "permission": "dha.registry"
    }
  },
  "/api/v1/dha/registries/practitioners": {
    "get": {
      "summary": "Get dha registries practitioners",
      "tag": "DHA",
      "permission": "dha.registry"
    }
  },
  "/api/v1/dha/status": {
    "get": {
      "summary": "Get dha status",
      "tag": "DHA",
      "permission": "dha.view"
    }
  },
  "/api/v1/diagnoses": {
    "get": {
      "summary": "Get diagnoses",
      "tag": "Diagnoses"
    },
    "post": {
      "summary": "Create/perform diagnoses",
      "tag": "Diagnoses"
    }
  },
  "/api/v1/diagnoses/{id}": {
    "patch": {
      "summary": "Update diagnoses",
      "tag": "Diagnoses"
    }
  },
  "/api/v1/diagnoses/import": {
    "post": {
      "summary": "Create/perform diagnoses import",
      "tag": "Diagnoses"
    }
  },
  "/api/v1/diagnoses/import-template": {
    "get": {
      "summary": "Get diagnoses import template",
      "tag": "Diagnoses"
    }
  },
  "/api/v1/diagnoses/suggest": {
    "get": {
      "summary": "Get diagnoses suggest",
      "tag": "Diagnoses"
    }
  },
  "/api/v1/documents": {
    "post": {
      "summary": "Create/perform documents",
      "tag": "Documents",
      "permission": "documents.upload"
    },
    "get": {
      "summary": "Get documents",
      "tag": "Documents",
      "permission": "documents.view"
    }
  },
  "/api/v1/documents/{id}/delete": {
    "post": {
      "summary": "Create/perform documents delete",
      "tag": "Documents",
      "permission": "documents.upload"
    }
  },
  "/api/v1/documents/{id}/download": {
    "get": {
      "summary": "Get documents download",
      "tag": "Documents",
      "permission": "documents.view"
    }
  },
  "/api/v1/family-planning/defaulters": {
    "get": {
      "summary": "Get family planning defaulters",
      "tag": "Family planning",
      "permission": "fp.view"
    }
  },
  "/api/v1/family-planning/visits": {
    "post": {
      "summary": "Create/perform family planning visits",
      "tag": "Family planning",
      "permission": "fp.manage"
    },
    "get": {
      "summary": "Get family planning visits",
      "tag": "Family planning",
      "permission": "fp.view"
    }
  },
  "/api/v1/fhir/Encounter/{id}": {
    "get": {
      "summary": "Get fhir Encounter",
      "tag": "FHIR",
      "permission": "consultation.view | dha.fhir"
    }
  },
  "/api/v1/fhir/Location": {
    "get": {
      "summary": "Get fhir Location",
      "tag": "FHIR",
      "permission": "dha.fhir | admin.settings"
    }
  },
  "/api/v1/fhir/metadata": {
    "get": {
      "summary": "Get fhir metadata",
      "tag": "FHIR"
    }
  },
  "/api/v1/fhir/Organization": {
    "get": {
      "summary": "Get fhir Organization",
      "tag": "FHIR",
      "permission": "dha.fhir | admin.settings"
    }
  },
  "/api/v1/fhir/outbox": {
    "get": {
      "summary": "Get fhir outbox",
      "tag": "FHIR",
      "permission": "dha.fhir"
    }
  },
  "/api/v1/fhir/outbox/{id}": {
    "get": {
      "summary": "Get fhir outbox",
      "tag": "FHIR",
      "permission": "dha.fhir"
    }
  },
  "/api/v1/fhir/outbox/{id}/retry": {
    "post": {
      "summary": "Create/perform fhir outbox retry",
      "tag": "FHIR",
      "permission": "dha.fhir"
    }
  },
  "/api/v1/fhir/Patient/{id}": {
    "get": {
      "summary": "Get fhir Patient",
      "tag": "FHIR",
      "permission": "patients.view | dha.fhir"
    }
  },
  "/api/v1/fhir/Patient/{id}/$everything": {
    "get": {
      "summary": "Get fhir Patient everything",
      "tag": "FHIR",
      "permission": "patients.view | consultation.view | dha.fhir"
    }
  },
  "/api/v1/fhir/Practitioner/{id}": {
    "get": {
      "summary": "Get fhir Practitioner",
      "tag": "FHIR",
      "permission": "admin.users | dha.fhir | hr.view"
    }
  },
  "/api/v1/finance/expenses": {
    "post": {
      "summary": "Create/perform finance expenses",
      "tag": "Finance",
      "permission": "finance.manage"
    },
    "get": {
      "summary": "Get finance expenses",
      "tag": "Finance",
      "permission": "finance.view"
    }
  },
  "/api/v1/finance/expenses/{id}/{decision}": {
    "post": {
      "summary": "Create/perform finance expenses",
      "tag": "Finance",
      "permission": "finance.manage"
    }
  },
  "/api/v1/finance/summary": {
    "get": {
      "summary": "Get finance summary",
      "tag": "Finance",
      "permission": "finance.view | reports.view"
    }
  },
  "/api/v1/hr/leave": {
    "post": {
      "summary": "Create/perform hr leave",
      "tag": "HR"
    },
    "get": {
      "summary": "Get hr leave",
      "tag": "HR",
      "permission": "hr.view"
    }
  },
  "/api/v1/hr/leave/{id}/{decision}": {
    "post": {
      "summary": "Create/perform hr leave",
      "tag": "HR",
      "permission": "hr.manage"
    }
  },
  "/api/v1/hr/leave/mine": {
    "get": {
      "summary": "Get hr leave mine",
      "tag": "HR"
    }
  },
  "/api/v1/hr/shifts": {
    "post": {
      "summary": "Create/perform hr shifts",
      "tag": "HR",
      "permission": "hr.manage"
    },
    "get": {
      "summary": "Get hr shifts",
      "tag": "HR",
      "permission": "hr.view"
    }
  },
  "/api/v1/hr/staff": {
    "get": {
      "summary": "Get hr staff",
      "tag": "HR",
      "permission": "hr.view"
    },
    "post": {
      "summary": "Create/perform hr staff",
      "tag": "HR",
      "permission": "hr.manage"
    }
  },
  "/api/v1/hr/staff/{id}": {
    "patch": {
      "summary": "Update hr staff",
      "tag": "HR",
      "permission": "hr.manage"
    }
  },
  "/api/v1/hr/staff/{id}/verify-registry": {
    "post": {
      "summary": "Create/perform hr staff verify registry",
      "tag": "HR",
      "permission": "hr.manage"
    }
  },
  "/api/v1/hr/staff/license-alerts": {
    "get": {
      "summary": "Get hr staff license alerts",
      "tag": "HR",
      "permission": "hr.view"
    }
  },
  "/api/v1/inpatient/admissions": {
    "post": {
      "summary": "Create/perform inpatient admissions",
      "tag": "Inpatient",
      "permission": "inpatient.admit"
    },
    "get": {
      "summary": "Get inpatient admissions",
      "tag": "Inpatient",
      "permission": "inpatient.view | nursing.view"
    }
  },
  "/api/v1/inpatient/admissions/{id}": {
    "get": {
      "summary": "Get inpatient admissions",
      "tag": "Inpatient",
      "permission": "inpatient.view | nursing.view"
    }
  },
  "/api/v1/inpatient/admissions/{id}/discharge": {
    "post": {
      "summary": "Create/perform inpatient admissions discharge",
      "tag": "Inpatient",
      "permission": "inpatient.discharge"
    }
  },
  "/api/v1/inpatient/admissions/{id}/fluids": {
    "post": {
      "summary": "Create/perform inpatient admissions fluids",
      "tag": "Inpatient",
      "permission": "nursing.record"
    }
  },
  "/api/v1/inpatient/admissions/{id}/mar": {
    "post": {
      "summary": "Create/perform inpatient admissions mar",
      "tag": "Inpatient",
      "permission": "nursing.record"
    }
  },
  "/api/v1/inpatient/admissions/{id}/notes": {
    "post": {
      "summary": "Create/perform inpatient admissions notes",
      "tag": "Inpatient",
      "permission": "nursing.record | consultation.create"
    }
  },
  "/api/v1/inpatient/admissions/{id}/transfer": {
    "post": {
      "summary": "Create/perform inpatient admissions transfer",
      "tag": "Inpatient",
      "permission": "inpatient.transfer"
    }
  },
  "/api/v1/inpatient/admissions/phone-otp": {
    "post": {
      "summary": "Create/perform inpatient admissions phone otp",
      "tag": "Inpatient",
      "permission": "inpatient.admit"
    }
  },
  "/api/v1/inpatient/admissions/phone-otp/{id}/verify": {
    "post": {
      "summary": "Create/perform inpatient admissions phone otp verify",
      "tag": "Inpatient",
      "permission": "inpatient.admit"
    }
  },
  "/api/v1/inpatient/admissions/phone-verification": {
    "get": {
      "summary": "Get inpatient admissions phone verification",
      "tag": "Inpatient",
      "permission": "inpatient.admit"
    }
  },
  "/api/v1/inpatient/beds": {
    "get": {
      "summary": "Get inpatient beds",
      "tag": "Inpatient",
      "permission": "inpatient.view | inpatient.manage | nursing.view"
    }
  },
  "/api/v1/inpatient/beds/{id}/status": {
    "post": {
      "summary": "Create/perform inpatient beds status",
      "tag": "Inpatient",
      "permission": "inpatient.manage | nursing.record"
    }
  },
  "/api/v1/inpatient/occupancy": {
    "get": {
      "summary": "Get inpatient occupancy",
      "tag": "Inpatient",
      "permission": "inpatient.view | reports.view | sha.view"
    }
  },
  "/api/v1/inpatient/wards": {
    "get": {
      "summary": "Get inpatient wards",
      "tag": "Inpatient",
      "permission": "inpatient.view | inpatient.manage | nursing.view"
    },
    "post": {
      "summary": "Create/perform inpatient wards",
      "tag": "Inpatient",
      "permission": "inpatient.manage"
    }
  },
  "/api/v1/inpatient/wards/{id}": {
    "patch": {
      "summary": "Update inpatient wards",
      "tag": "Inpatient",
      "permission": "inpatient.manage"
    }
  },
  "/api/v1/inpatient/wards/{id}/beds": {
    "post": {
      "summary": "Create/perform inpatient wards beds",
      "tag": "Inpatient",
      "permission": "inpatient.manage"
    }
  },
  "/api/v1/insurance/claims": {
    "get": {
      "summary": "Get insurance claims",
      "tag": "Insurance",
      "permission": "insurance.view"
    }
  },
  "/api/v1/insurance/claims/{id}": {
    "get": {
      "summary": "Get insurance claims",
      "tag": "Insurance",
      "permission": "insurance.view"
    }
  },
  "/api/v1/insurance/claims/{id}/attachments": {
    "post": {
      "summary": "Create/perform insurance claims attachments",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/claims/{id}/credit-notes": {
    "post": {
      "summary": "Create/perform insurance claims credit notes",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/claims/{id}/invoice": {
    "post": {
      "summary": "Create/perform insurance claims invoice",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/claims/{id}/reconcile": {
    "post": {
      "summary": "Create/perform insurance claims reconcile",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/claims/{id}/refresh-status": {
    "post": {
      "summary": "Create/perform insurance claims refresh status",
      "tag": "Insurance",
      "permission": "insurance.view"
    }
  },
  "/api/v1/insurance/claims/{id}/remittance": {
    "post": {
      "summary": "Create/perform insurance claims remittance",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/code-maps": {
    "get": {
      "summary": "Get insurance code maps",
      "tag": "Insurance",
      "permission": "insurance.view"
    },
    "post": {
      "summary": "Create/perform insurance code maps",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/coverages": {
    "get": {
      "summary": "Get insurance coverages",
      "tag": "Insurance",
      "permission": "insurance.view"
    },
    "post": {
      "summary": "Create/perform insurance coverages",
      "tag": "Insurance",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/insurance/coverages/{id}": {
    "patch": {
      "summary": "Update insurance coverages",
      "tag": "Insurance",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/insurance/coverages/{id}/deactivate": {
    "post": {
      "summary": "Create/perform insurance coverages deactivate",
      "tag": "Insurance",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/insurance/coverages/{id}/eligibility": {
    "post": {
      "summary": "Create/perform insurance coverages eligibility",
      "tag": "Insurance",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/insurance/dashboard": {
    "get": {
      "summary": "Get insurance dashboard",
      "tag": "Insurance",
      "permission": "insurance.view"
    }
  },
  "/api/v1/insurance/payers": {
    "get": {
      "summary": "Get insurance payers",
      "tag": "Insurance",
      "permission": "insurance.view"
    },
    "post": {
      "summary": "Create/perform insurance payers",
      "tag": "Insurance",
      "permission": "insurance.manage | admin.integrations"
    }
  },
  "/api/v1/insurance/payers/{id}": {
    "patch": {
      "summary": "Update insurance payers",
      "tag": "Insurance",
      "permission": "insurance.manage | admin.integrations"
    }
  },
  "/api/v1/insurance/payers/sandbox-examples": {
    "post": {
      "summary": "Create/perform insurance payers sandbox examples",
      "tag": "Insurance",
      "permission": "insurance.manage | admin.integrations"
    }
  },
  "/api/v1/insurance/providers": {
    "get": {
      "summary": "Get insurance providers",
      "tag": "Insurance",
      "permission": "insurance.view"
    }
  },
  "/api/v1/insurance/remittances": {
    "get": {
      "summary": "Get insurance remittances",
      "tag": "Insurance",
      "permission": "insurance.view"
    }
  },
  "/api/v1/insurance/remittances/sync": {
    "post": {
      "summary": "Create/perform insurance remittances sync",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/slade360/test-connection": {
    "post": {
      "summary": "Create/perform insurance slade360 test connection",
      "tag": "Insurance",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/insurance/visits": {
    "get": {
      "summary": "Get insurance visits",
      "tag": "Insurance",
      "permission": "insurance.view"
    }
  },
  "/api/v1/insurance/visits/{id}": {
    "get": {
      "summary": "Get insurance visits",
      "tag": "Insurance",
      "permission": "insurance.view"
    }
  },
  "/api/v1/insurance/visits/{id}/claim": {
    "post": {
      "summary": "Create/perform insurance visits claim",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/visits/{id}/reserve": {
    "post": {
      "summary": "Create/perform insurance visits reserve",
      "tag": "Insurance",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/insurance/visits/{id}/validate-authorization": {
    "post": {
      "summary": "Create/perform insurance visits validate authorization",
      "tag": "Insurance",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/integrations/claims": {
    "get": {
      "summary": "Get integrations claims",
      "tag": "Integrations",
      "permission": "insurance.view"
    }
  },
  "/api/v1/integrations/claims/{id}": {
    "get": {
      "summary": "Get integrations claims",
      "tag": "Integrations",
      "permission": "insurance.view"
    }
  },
  "/api/v1/integrations/claims/{id}/attachments": {
    "post": {
      "summary": "Create/perform integrations claims attachments",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/claims/{id}/credit-notes": {
    "post": {
      "summary": "Create/perform integrations claims credit notes",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/claims/{id}/invoice": {
    "post": {
      "summary": "Create/perform integrations claims invoice",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/claims/{id}/reconcile": {
    "post": {
      "summary": "Create/perform integrations claims reconcile",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/claims/{id}/refresh-status": {
    "post": {
      "summary": "Create/perform integrations claims refresh status",
      "tag": "Integrations",
      "permission": "insurance.view"
    }
  },
  "/api/v1/integrations/claims/{id}/remittance": {
    "post": {
      "summary": "Create/perform integrations claims remittance",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/code-maps": {
    "get": {
      "summary": "Get integrations code maps",
      "tag": "Integrations",
      "permission": "insurance.view"
    },
    "post": {
      "summary": "Create/perform integrations code maps",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/coverages": {
    "get": {
      "summary": "Get integrations coverages",
      "tag": "Integrations",
      "permission": "insurance.view"
    },
    "post": {
      "summary": "Create/perform integrations coverages",
      "tag": "Integrations",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/integrations/coverages/{id}": {
    "patch": {
      "summary": "Update integrations coverages",
      "tag": "Integrations",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/integrations/coverages/{id}/deactivate": {
    "post": {
      "summary": "Create/perform integrations coverages deactivate",
      "tag": "Integrations",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/integrations/coverages/{id}/eligibility": {
    "post": {
      "summary": "Create/perform integrations coverages eligibility",
      "tag": "Integrations",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/integrations/dashboard": {
    "get": {
      "summary": "Get integrations dashboard",
      "tag": "Integrations",
      "permission": "insurance.view"
    }
  },
  "/api/v1/integrations/payers": {
    "get": {
      "summary": "Get integrations payers",
      "tag": "Integrations",
      "permission": "insurance.view"
    },
    "post": {
      "summary": "Create/perform integrations payers",
      "tag": "Integrations",
      "permission": "insurance.manage | admin.integrations"
    }
  },
  "/api/v1/integrations/payers/{id}": {
    "patch": {
      "summary": "Update integrations payers",
      "tag": "Integrations",
      "permission": "insurance.manage | admin.integrations"
    }
  },
  "/api/v1/integrations/payers/sandbox-examples": {
    "post": {
      "summary": "Create/perform integrations payers sandbox examples",
      "tag": "Integrations",
      "permission": "insurance.manage | admin.integrations"
    }
  },
  "/api/v1/integrations/providers": {
    "get": {
      "summary": "Get integrations providers",
      "tag": "Integrations",
      "permission": "insurance.view"
    }
  },
  "/api/v1/integrations/remittances": {
    "get": {
      "summary": "Get integrations remittances",
      "tag": "Integrations",
      "permission": "insurance.view"
    }
  },
  "/api/v1/integrations/remittances/sync": {
    "post": {
      "summary": "Create/perform integrations remittances sync",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/slade360/test-connection": {
    "post": {
      "summary": "Create/perform integrations slade360 test connection",
      "tag": "Integrations",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/integrations/visits": {
    "get": {
      "summary": "Get integrations visits",
      "tag": "Integrations",
      "permission": "insurance.view"
    }
  },
  "/api/v1/integrations/visits/{id}": {
    "get": {
      "summary": "Get integrations visits",
      "tag": "Integrations",
      "permission": "insurance.view"
    }
  },
  "/api/v1/integrations/visits/{id}/claim": {
    "post": {
      "summary": "Create/perform integrations visits claim",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/visits/{id}/reserve": {
    "post": {
      "summary": "Create/perform integrations visits reserve",
      "tag": "Integrations",
      "permission": "insurance.manage"
    }
  },
  "/api/v1/integrations/visits/{id}/validate-authorization": {
    "post": {
      "summary": "Create/perform integrations visits validate authorization",
      "tag": "Integrations",
      "permission": "insurance.eligibility"
    }
  },
  "/api/v1/inventory/items": {
    "get": {
      "summary": "Get inventory items",
      "tag": "Inventory"
    },
    "post": {
      "summary": "Create/perform inventory items",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/items/{id}": {
    "patch": {
      "summary": "Update inventory items",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/items/import": {
    "post": {
      "summary": "Create/perform inventory items import",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/items/import-template": {
    "get": {
      "summary": "Get inventory items import template",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/locations": {
    "get": {
      "summary": "Get inventory locations",
      "tag": "Inventory"
    },
    "post": {
      "summary": "Create/perform inventory locations",
      "tag": "Inventory",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/inventory/prescriptions": {
    "post": {
      "summary": "Create/perform inventory prescriptions",
      "tag": "Inventory",
      "permission": "prescription.create"
    },
    "get": {
      "summary": "Get inventory prescriptions",
      "tag": "Inventory",
      "permission": "pharmacy.view | prescription.create | nursing.view"
    }
  },
  "/api/v1/inventory/prescriptions/{id}": {
    "get": {
      "summary": "Get inventory prescriptions",
      "tag": "Inventory",
      "permission": "pharmacy.view | prescription.create"
    }
  },
  "/api/v1/inventory/prescriptions/{id}/cancel": {
    "post": {
      "summary": "Create/perform inventory prescriptions cancel",
      "tag": "Inventory",
      "permission": "prescription.create | pharmacy.dispense"
    }
  },
  "/api/v1/inventory/prescriptions/{id}/dispense": {
    "post": {
      "summary": "Create/perform inventory prescriptions dispense",
      "tag": "Inventory",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/inventory/prescriptions/{id}/receive": {
    "post": {
      "summary": "Create/perform inventory prescriptions receive",
      "tag": "Inventory",
      "permission": "nursing.record"
    }
  },
  "/api/v1/inventory/prescriptions/{id}/return": {
    "post": {
      "summary": "Create/perform inventory prescriptions return",
      "tag": "Inventory",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/inventory/requisition-items": {
    "get": {
      "summary": "Get inventory requisition items",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/requisition-locations": {
    "get": {
      "summary": "Get inventory requisition locations",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/requisitions": {
    "get": {
      "summary": "Get inventory requisitions",
      "tag": "Inventory"
    },
    "post": {
      "summary": "Create/perform inventory requisitions",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/requisitions/{id}": {
    "get": {
      "summary": "Get inventory requisitions",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/requisitions/{id}/cancel": {
    "post": {
      "summary": "Create/perform inventory requisitions cancel",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/requisitions/{id}/decide": {
    "post": {
      "summary": "Create/perform inventory requisitions decide",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/requisitions/{id}/issue": {
    "post": {
      "summary": "Create/perform inventory requisitions issue",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/requisitions/{id}/receive": {
    "post": {
      "summary": "Create/perform inventory requisitions receive",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock": {
    "get": {
      "summary": "Get inventory stock",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock-takes": {
    "get": {
      "summary": "Get inventory stock takes",
      "tag": "Inventory",
      "permission": "inventory.view"
    },
    "post": {
      "summary": "Create/perform inventory stock takes",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock-takes/{id}": {
    "get": {
      "summary": "Get inventory stock takes",
      "tag": "Inventory",
      "permission": "inventory.view"
    }
  },
  "/api/v1/inventory/stock-takes/{id}/approve": {
    "post": {
      "summary": "Create/perform inventory stock takes approve",
      "tag": "Inventory",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/inventory/stock-takes/{id}/cancel": {
    "post": {
      "summary": "Create/perform inventory stock takes cancel",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock-takes/{id}/counts": {
    "put": {
      "summary": "Replace inventory stock takes counts",
      "tag": "Inventory",
      "permission": "inventory.view"
    }
  },
  "/api/v1/inventory/stock/adjust": {
    "post": {
      "summary": "Create/perform inventory stock adjust",
      "tag": "Inventory",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/inventory/stock/expiring": {
    "get": {
      "summary": "Get inventory stock expiring",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/movement-report": {
    "get": {
      "summary": "Get inventory stock movement report",
      "tag": "Inventory",
      "permission": "inventory.view | pharmacy.view"
    }
  },
  "/api/v1/inventory/stock/movements": {
    "get": {
      "summary": "Get inventory stock movements",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/receive": {
    "post": {
      "summary": "Create/perform inventory stock receive",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/reorder-suggestions": {
    "get": {
      "summary": "Get inventory stock reorder suggestions",
      "tag": "Inventory",
      "permission": "inventory.view | procurement.view | procurement.manage | lab.manage"
    }
  },
  "/api/v1/inventory/stock/summary": {
    "get": {
      "summary": "Get inventory stock summary",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/transfer": {
    "post": {
      "summary": "Create/perform inventory stock transfer",
      "tag": "Inventory"
    }
  },
  "/api/v1/laboratory/accession/{accession}": {
    "get": {
      "summary": "Get laboratory accession",
      "tag": "Laboratory",
      "permission": "lab.view"
    }
  },
  "/api/v1/laboratory/orders": {
    "post": {
      "summary": "Create/perform laboratory orders",
      "tag": "Laboratory",
      "permission": "lab.order"
    },
    "get": {
      "summary": "Get laboratory orders",
      "tag": "Laboratory",
      "permission": "lab.view"
    }
  },
  "/api/v1/laboratory/orders/{id}": {
    "get": {
      "summary": "Get laboratory orders",
      "tag": "Laboratory",
      "permission": "lab.view"
    }
  },
  "/api/v1/laboratory/orders/{id}/items/{itemId}/{step}": {
    "post": {
      "summary": "Create/perform laboratory orders items",
      "tag": "Laboratory"
    }
  },
  "/api/v1/laboratory/orders/{id}/report": {
    "get": {
      "summary": "Get laboratory orders report",
      "tag": "Laboratory",
      "permission": "lab.view"
    }
  },
  "/api/v1/laboratory/packages": {
    "get": {
      "summary": "Get laboratory packages",
      "tag": "Laboratory",
      "permission": "lab.view | lab.order | lab.walkin"
    },
    "post": {
      "summary": "Create/perform laboratory packages",
      "tag": "Laboratory",
      "permission": "lab.manage"
    }
  },
  "/api/v1/laboratory/packages/{code}": {
    "patch": {
      "summary": "Update laboratory packages",
      "tag": "Laboratory",
      "permission": "lab.manage"
    }
  },
  "/api/v1/laboratory/tests": {
    "get": {
      "summary": "Get laboratory tests",
      "tag": "Laboratory",
      "permission": "lab.view"
    },
    "post": {
      "summary": "Create/perform laboratory tests",
      "tag": "Laboratory",
      "permission": "lab.manage"
    }
  },
  "/api/v1/laboratory/tests/{code}": {
    "patch": {
      "summary": "Update laboratory tests",
      "tag": "Laboratory",
      "permission": "lab.manage"
    }
  },
  "/api/v1/laboratory/tests/import": {
    "post": {
      "summary": "Create/perform laboratory tests import",
      "tag": "Laboratory",
      "permission": "lab.manage"
    }
  },
  "/api/v1/laboratory/tests/import-template": {
    "get": {
      "summary": "Get laboratory tests import template",
      "tag": "Laboratory",
      "permission": "lab.manage"
    }
  },
  "/api/v1/laboratory/walk-in": {
    "post": {
      "summary": "Create/perform laboratory walk in",
      "tag": "Laboratory",
      "permission": "lab.walkin"
    }
  },
  "/api/v1/maternity/birth-notifications": {
    "get": {
      "summary": "Get maternity birth notifications",
      "tag": "Maternity",
      "permission": "maternity.view | mch.view"
    }
  },
  "/api/v1/maternity/birth-notifications/{id}": {
    "get": {
      "summary": "Get maternity birth notifications",
      "tag": "Maternity",
      "permission": "maternity.view | mch.view"
    },
    "patch": {
      "summary": "Update maternity birth notifications",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/maternity/birth-notifications/{id}/printed": {
    "post": {
      "summary": "Create/perform maternity birth notifications printed",
      "tag": "Maternity",
      "permission": "maternity.view | maternity.manage"
    }
  },
  "/api/v1/maternity/deliveries/{id}/birth-notifications": {
    "get": {
      "summary": "Get maternity deliveries birth notifications",
      "tag": "Maternity",
      "permission": "maternity.view | mch.view"
    },
    "post": {
      "summary": "Create/perform maternity deliveries birth notifications",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/maternity/labour/{id}/partograph": {
    "post": {
      "summary": "Create/perform maternity labour partograph",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/maternity/pnc": {
    "post": {
      "summary": "Create/perform maternity pnc",
      "tag": "Maternity",
      "permission": "maternity.manage | mch.manage"
    }
  },
  "/api/v1/maternity/pregnancies": {
    "post": {
      "summary": "Create/perform maternity pregnancies",
      "tag": "Maternity",
      "permission": "maternity.manage"
    },
    "get": {
      "summary": "Get maternity pregnancies",
      "tag": "Maternity",
      "permission": "maternity.view | mch.view"
    }
  },
  "/api/v1/maternity/pregnancies/{id}": {
    "get": {
      "summary": "Get maternity pregnancies",
      "tag": "Maternity",
      "permission": "maternity.view | mch.view"
    }
  },
  "/api/v1/maternity/pregnancies/{id}/anc": {
    "post": {
      "summary": "Create/perform maternity pregnancies anc",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/maternity/pregnancies/{id}/delivery": {
    "post": {
      "summary": "Create/perform maternity pregnancies delivery",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/maternity/pregnancies/{id}/labour": {
    "post": {
      "summary": "Create/perform maternity pregnancies labour",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/mch/defaulters": {
    "get": {
      "summary": "Get mch defaulters",
      "tag": "MCH",
      "permission": "mch.view"
    }
  },
  "/api/v1/mch/growth": {
    "post": {
      "summary": "Create/perform mch growth",
      "tag": "MCH",
      "permission": "mch.manage"
    }
  },
  "/api/v1/mch/immunizations": {
    "post": {
      "summary": "Create/perform mch immunizations",
      "tag": "MCH",
      "permission": "mch.manage"
    }
  },
  "/api/v1/mch/patients/{id}/growth": {
    "get": {
      "summary": "Get mch patients growth",
      "tag": "MCH",
      "permission": "mch.view | maternity.view"
    }
  },
  "/api/v1/mch/patients/{id}/immunizations": {
    "get": {
      "summary": "Get mch patients immunizations",
      "tag": "MCH",
      "permission": "mch.view | maternity.view"
    }
  },
  "/api/v1/medical-reports": {
    "get": {
      "summary": "Get medical reports",
      "tag": "Medical reports",
      "permission": "medicalreports.view"
    },
    "post": {
      "summary": "Create/perform medical reports",
      "tag": "Medical reports",
      "permission": "medicalreports.create"
    }
  },
  "/api/v1/medical-reports/{id}": {
    "get": {
      "summary": "Get medical reports",
      "tag": "Medical reports",
      "permission": "medicalreports.view"
    },
    "put": {
      "summary": "Replace medical reports",
      "tag": "Medical reports",
      "permission": "medicalreports.create"
    }
  },
  "/api/v1/medical-reports/{id}/addendum": {
    "post": {
      "summary": "Create/perform medical reports addendum",
      "tag": "Medical reports",
      "permission": "medicalreports.create"
    }
  },
  "/api/v1/medical-reports/{id}/finalize": {
    "post": {
      "summary": "Create/perform medical reports finalize",
      "tag": "Medical reports",
      "permission": "medicalreports.create"
    }
  },
  "/api/v1/medical-reports/{id}/void": {
    "post": {
      "summary": "Create/perform medical reports void",
      "tag": "Medical reports",
      "permission": "medicalreports.create"
    }
  },
  "/api/v1/mortuary/cases": {
    "post": {
      "summary": "Create/perform mortuary cases",
      "tag": "Mortuary",
      "permission": "mortuary.manage"
    },
    "get": {
      "summary": "Get mortuary cases",
      "tag": "Mortuary",
      "permission": "mortuary.view"
    }
  },
  "/api/v1/mortuary/cases/{id}": {
    "get": {
      "summary": "Get mortuary cases",
      "tag": "Mortuary",
      "permission": "mortuary.view"
    },
    "patch": {
      "summary": "Update mortuary cases",
      "tag": "Mortuary",
      "permission": "mortuary.manage"
    }
  },
  "/api/v1/mortuary/cases/{id}/authorize-release": {
    "post": {
      "summary": "Create/perform mortuary cases authorize release",
      "tag": "Mortuary",
      "permission": "mortuary.release"
    }
  },
  "/api/v1/mortuary/cases/{id}/release": {
    "post": {
      "summary": "Create/perform mortuary cases release",
      "tag": "Mortuary",
      "permission": "mortuary.manage"
    }
  },
  "/api/v1/notifications": {
    "get": {
      "summary": "Get notifications",
      "tag": "Notifications"
    }
  },
  "/api/v1/notifications/{id}/read": {
    "post": {
      "summary": "Create/perform notifications read",
      "tag": "Notifications"
    }
  },
  "/api/v1/notifications/read-all": {
    "post": {
      "summary": "Create/perform notifications read all",
      "tag": "Notifications"
    }
  },
  "/api/v1/oauth/google/callback": {
    "get": {
      "summary": "Get oauth google callback",
      "tag": "Google"
    }
  },
  "/api/v1/onboarding/applications": {
    "post": {
      "summary": "Create/perform onboarding applications",
      "tag": "Onboarding"
    }
  },
  "/api/v1/onboarding/applications/resend": {
    "post": {
      "summary": "Create/perform onboarding applications resend",
      "tag": "Onboarding"
    }
  },
  "/api/v1/onboarding/applications/status": {
    "post": {
      "summary": "Create/perform onboarding applications status",
      "tag": "Onboarding"
    }
  },
  "/api/v1/onboarding/applications/verify": {
    "post": {
      "summary": "Create/perform onboarding applications verify",
      "tag": "Onboarding"
    }
  },
  "/api/v1/onboarding/config": {
    "get": {
      "summary": "Get onboarding config",
      "tag": "Onboarding"
    }
  },
  "/api/v1/onboarding/slug": {
    "get": {
      "summary": "Get onboarding slug",
      "tag": "Onboarding"
    }
  },
  "/api/v1/opd/diagnoses/search": {
    "get": {
      "summary": "Get opd diagnoses search",
      "tag": "OPD",
      "permission": "consultation.create | consultation.view"
    }
  },
  "/api/v1/opd/patients/{patientId}/summary": {
    "get": {
      "summary": "Get opd patients summary",
      "tag": "OPD",
      "permission": "consultation.view | opd.view | nursing.view"
    }
  },
  "/api/v1/opd/procedures": {
    "post": {
      "summary": "Create/perform opd procedures",
      "tag": "OPD",
      "permission": "consultation.create | nursing.record | dental.manage"
    }
  },
  "/api/v1/opd/procedures/{id}/{action}": {
    "post": {
      "summary": "Create/perform opd procedures",
      "tag": "OPD",
      "permission": "consultation.create | nursing.record | dental.manage"
    }
  },
  "/api/v1/opd/vitals": {
    "post": {
      "summary": "Create/perform opd vitals",
      "tag": "OPD",
      "permission": "opd.create | nursing.record"
    },
    "get": {
      "summary": "Get opd vitals",
      "tag": "OPD",
      "permission": "opd.view | nursing.view | consultation.view"
    }
  },
  "/api/v1/owner/announcements": {
    "get": {
      "summary": "Get owner announcements",
      "tag": "Owner"
    },
    "post": {
      "summary": "Create/perform owner announcements",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/announcements/{id}": {
    "get": {
      "summary": "Get owner announcements",
      "tag": "Owner"
    },
    "put": {
      "summary": "Replace owner announcements",
      "tag": "Owner"
    },
    "delete": {
      "summary": "Delete owner announcements",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/audit": {
    "get": {
      "summary": "Get owner audit",
      "tag": "Owner",
      "permission": "owner.logs"
    }
  },
  "/api/v1/owner/auth/change-password": {
    "post": {
      "summary": "Create/perform owner auth change password",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/auth/login": {
    "post": {
      "summary": "Create/perform owner auth login",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/auth/logout": {
    "post": {
      "summary": "Create/perform owner auth logout",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/auth/me": {
    "get": {
      "summary": "Get owner auth me",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/auth/refresh": {
    "post": {
      "summary": "Create/perform owner auth refresh",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/backups": {
    "get": {
      "summary": "Get owner backups",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/owner/billing/assets/{kind}": {
    "post": {
      "summary": "Create/perform owner billing assets",
      "tag": "Owner",
      "permission": "owner.platform"
    },
    "delete": {
      "summary": "Delete owner billing assets",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/owner/billing/assets/file/{id}": {
    "get": {
      "summary": "Get owner billing assets file",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents": {
    "get": {
      "summary": "Get owner billing documents",
      "tag": "Owner"
    },
    "post": {
      "summary": "Create/perform owner billing documents",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents/{id}": {
    "get": {
      "summary": "Get owner billing documents",
      "tag": "Owner"
    },
    "patch": {
      "summary": "Update owner billing documents",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents/{id}/convert": {
    "post": {
      "summary": "Create/perform owner billing documents convert",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents/{id}/issue": {
    "post": {
      "summary": "Create/perform owner billing documents issue",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents/{id}/payments": {
    "post": {
      "summary": "Create/perform owner billing documents payments",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents/{id}/pdf": {
    "get": {
      "summary": "Get owner billing documents pdf",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents/{id}/send": {
    "post": {
      "summary": "Create/perform owner billing documents send",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents/{id}/stk": {
    "post": {
      "summary": "Create/perform owner billing documents stk",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/documents/{id}/void": {
    "post": {
      "summary": "Create/perform owner billing documents void",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/mpesa/register-c2b": {
    "post": {
      "summary": "Create/perform owner billing mpesa register c2b",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/billing/payments": {
    "get": {
      "summary": "Get owner billing payments",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/payments/{id}": {
    "get": {
      "summary": "Get owner billing payments",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/payments/{id}/allocate": {
    "post": {
      "summary": "Create/perform owner billing payments allocate",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/billing/settings": {
    "get": {
      "summary": "Get owner billing settings",
      "tag": "Owner"
    },
    "put": {
      "summary": "Replace owner billing settings",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/owner/blog/images": {
    "post": {
      "summary": "Create/perform owner blog images",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/blog/posts": {
    "get": {
      "summary": "Get owner blog posts",
      "tag": "Owner"
    },
    "post": {
      "summary": "Create/perform owner blog posts",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/blog/posts/{id}": {
    "get": {
      "summary": "Get owner blog posts",
      "tag": "Owner"
    },
    "put": {
      "summary": "Replace owner blog posts",
      "tag": "Owner"
    },
    "delete": {
      "summary": "Delete owner blog posts",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/contracts/{provider}": {
    "get": {
      "summary": "Get owner contracts",
      "tag": "Owner",
      "permission": "owner.integrations"
    },
    "patch": {
      "summary": "Update owner contracts",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/dashboard": {
    "get": {
      "summary": "Get owner dashboard",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/integration-logs": {
    "get": {
      "summary": "Get owner integration logs",
      "tag": "Owner",
      "permission": "owner.logs"
    }
  },
  "/api/v1/owner/integrations": {
    "get": {
      "summary": "Get owner integrations",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/integrations/{provider}": {
    "put": {
      "summary": "Replace owner integrations",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/integrations/{provider}/test": {
    "post": {
      "summary": "Create/perform owner integrations test",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/jobs": {
    "get": {
      "summary": "Get owner jobs",
      "tag": "Owner",
      "permission": "owner.logs"
    }
  },
  "/api/v1/owner/jobs/{id}/retry": {
    "post": {
      "summary": "Create/perform owner jobs retry",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/onboarding/applications": {
    "get": {
      "summary": "Get owner onboarding applications",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/onboarding/applications/{id}/approve": {
    "post": {
      "summary": "Create/perform owner onboarding applications approve",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/onboarding/applications/{id}/reject": {
    "post": {
      "summary": "Create/perform owner onboarding applications reject",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/onboarding/settings": {
    "get": {
      "summary": "Get owner onboarding settings",
      "tag": "Owner",
      "permission": "owner.tenants"
    },
    "put": {
      "summary": "Replace owner onboarding settings",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/owner/plans": {
    "get": {
      "summary": "Get owner plans",
      "tag": "Owner",
      "permission": "owner.subscriptions"
    },
    "post": {
      "summary": "Create/perform owner plans",
      "tag": "Owner",
      "permission": "owner.subscriptions"
    }
  },
  "/api/v1/owner/plans/{key}": {
    "patch": {
      "summary": "Update owner plans",
      "tag": "Owner",
      "permission": "owner.subscriptions"
    }
  },
  "/api/v1/owner/plans/modules": {
    "get": {
      "summary": "Get owner plans modules",
      "tag": "Owner",
      "permission": "owner.subscriptions"
    }
  },
  "/api/v1/owner/security/mfa-policy": {
    "get": {
      "summary": "Get owner security mfa policy",
      "tag": "Owner",
      "permission": "owner.platform"
    },
    "put": {
      "summary": "Replace owner security mfa policy",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/owner/sha-callbacks": {
    "get": {
      "summary": "Get owner sha callbacks",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/sha-callbacks/active": {
    "post": {
      "summary": "Create/perform owner sha callbacks active",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/sha-callbacks/register": {
    "post": {
      "summary": "Create/perform owner sha callbacks register",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/sms/settings": {
    "get": {
      "summary": "Get owner sms settings",
      "tag": "Owner"
    },
    "put": {
      "summary": "Replace owner sms settings",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/sms/wallets": {
    "get": {
      "summary": "Get owner sms wallets",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/sms/wallets/{tenantId}/adjust": {
    "post": {
      "summary": "Create/perform owner sms wallets adjust",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/sms/wallets/{tenantId}/ledger": {
    "get": {
      "summary": "Get owner sms wallets ledger",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/support-access": {
    "post": {
      "summary": "Create/perform owner support access",
      "tag": "Owner",
      "permission": "owner.support"
    },
    "get": {
      "summary": "Get owner support access",
      "tag": "Owner",
      "permission": "owner.support"
    }
  },
  "/api/v1/owner/support-access/{id}/session": {
    "post": {
      "summary": "Create/perform owner support access session",
      "tag": "Owner",
      "permission": "owner.support"
    }
  },
  "/api/v1/owner/system/health": {
    "get": {
      "summary": "Get owner system health",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/tenants": {
    "get": {
      "summary": "Get owner tenants",
      "tag": "Owner",
      "permission": "owner.tenants"
    },
    "post": {
      "summary": "Create/perform owner tenants",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}": {
    "get": {
      "summary": "Get owner tenants",
      "tag": "Owner",
      "permission": "owner.tenants"
    },
    "patch": {
      "summary": "Update owner tenants",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/audit": {
    "get": {
      "summary": "Get owner tenants audit",
      "tag": "Owner",
      "permission": "owner.logs"
    }
  },
  "/api/v1/owner/tenants/{id}/branches": {
    "post": {
      "summary": "Create/perform owner tenants branches",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/branding": {
    "get": {
      "summary": "Get owner tenants branding",
      "tag": "Owner",
      "permission": "owner.tenants"
    },
    "put": {
      "summary": "Replace owner tenants branding",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/branding/logo": {
    "put": {
      "summary": "Replace owner tenants branding logo",
      "tag": "Owner",
      "permission": "owner.tenants"
    },
    "delete": {
      "summary": "Delete owner tenants branding logo",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/domains": {
    "post": {
      "summary": "Create/perform owner tenants domains",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/domains/{domainId}": {
    "delete": {
      "summary": "Delete owner tenants domains",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/domains/{domainId}/verify": {
    "post": {
      "summary": "Create/perform owner tenants domains verify",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/health": {
    "get": {
      "summary": "Get owner tenants health",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/integrations": {
    "put": {
      "summary": "Replace owner tenants integrations",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/tenants/{id}/reset-admin": {
    "post": {
      "summary": "Create/perform owner tenants reset admin",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/subscription": {
    "put": {
      "summary": "Replace owner tenants subscription",
      "tag": "Owner",
      "permission": "owner.subscriptions"
    }
  },
  "/api/v1/owner/users": {
    "get": {
      "summary": "Get owner users",
      "tag": "Owner",
      "permission": "owner.platform"
    },
    "post": {
      "summary": "Create/perform owner users",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/owner/users/{id}/mfa/reset": {
    "post": {
      "summary": "Create/perform owner users mfa reset",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/patients": {
    "get": {
      "summary": "Get patients",
      "tag": "Patients",
      "permission": "patients.view"
    },
    "post": {
      "summary": "Create/perform patients",
      "tag": "Patients",
      "permission": "patients.create"
    }
  },
  "/api/v1/patients/{id}": {
    "get": {
      "summary": "Get patients",
      "tag": "Patients",
      "permission": "patients.view"
    },
    "patch": {
      "summary": "Update patients",
      "tag": "Patients",
      "permission": "patients.edit"
    }
  },
  "/api/v1/patients/{id}/timeline": {
    "get": {
      "summary": "Get patients timeline",
      "tag": "Patients",
      "permission": "patients.view"
    }
  },
  "/api/v1/patients/duplicate-check": {
    "post": {
      "summary": "Create/perform patients duplicate check",
      "tag": "Patients",
      "permission": "patients.create | patients.search"
    }
  },
  "/api/v1/patients/import-dha": {
    "post": {
      "summary": "Create/perform patients import dha",
      "tag": "Patients",
      "permission": "patients.create | dha.registry"
    }
  },
  "/api/v1/patients/link-branch": {
    "post": {
      "summary": "Create/perform patients link branch",
      "tag": "Patients",
      "permission": "patients.create"
    }
  },
  "/api/v1/patients/search": {
    "get": {
      "summary": "Get patients search",
      "tag": "Patients",
      "permission": "patients.search"
    }
  },
  "/api/v1/payments/mpesa/{paymentId}/query": {
    "post": {
      "summary": "Create/perform payments mpesa query",
      "tag": "Payments",
      "permission": "billing.create"
    }
  },
  "/api/v1/payments/mpesa/c2b/{token}/confirmation": {
    "post": {
      "summary": "Create/perform payments mpesa c2b confirmation",
      "tag": "Billing",
      "public": true
    }
  },
  "/api/v1/payments/mpesa/c2b/{token}/validation": {
    "post": {
      "summary": "Create/perform payments mpesa c2b validation",
      "tag": "Billing",
      "public": true
    }
  },
  "/api/v1/payments/mpesa/c2b/register": {
    "post": {
      "summary": "Create/perform payments mpesa c2b register",
      "tag": "Payments",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/payments/mpesa/callback/{token}": {
    "post": {
      "summary": "Create/perform payments mpesa callback",
      "tag": "Billing",
      "public": true
    }
  },
  "/api/v1/payments/mpesa/refunds/{creditNoteId}/payout": {
    "post": {
      "summary": "Create/perform payments mpesa refunds payout",
      "tag": "Payments",
      "permission": "billing.refund"
    }
  },
  "/api/v1/payments/mpesa/stk": {
    "post": {
      "summary": "Create/perform payments mpesa stk",
      "tag": "Payments",
      "permission": "billing.create"
    }
  },
  "/api/v1/payments/payhero/callback/{token}": {
    "post": {
      "summary": "Create/perform payments payhero callback",
      "tag": "Billing",
      "public": true
    }
  },
  "/api/v1/payments/platform-mpesa/c2b/{token}/confirmation": {
    "post": {
      "summary": "Create/perform payments platform mpesa c2b confirmation",
      "tag": "PlatformBilling",
      "public": true
    }
  },
  "/api/v1/payments/platform-mpesa/c2b/{token}/validation": {
    "post": {
      "summary": "Create/perform payments platform mpesa c2b validation",
      "tag": "PlatformBilling",
      "public": true
    }
  },
  "/api/v1/payments/platform-mpesa/callback/{token}": {
    "post": {
      "summary": "Create/perform payments platform mpesa callback",
      "tag": "PlatformBilling",
      "public": true
    }
  },
  "/api/v1/payments/platform-payhero/callback/{token}": {
    "post": {
      "summary": "Create/perform payments platform payhero callback",
      "tag": "PlatformBilling",
      "public": true
    }
  },
  "/api/v1/pharmacy/items": {
    "get": {
      "summary": "Get pharmacy items",
      "tag": "Pharmacy"
    },
    "post": {
      "summary": "Create/perform pharmacy items",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/items/{id}": {
    "patch": {
      "summary": "Update pharmacy items",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/items/import": {
    "post": {
      "summary": "Create/perform pharmacy items import",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/items/import-template": {
    "get": {
      "summary": "Get pharmacy items import template",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/locations": {
    "get": {
      "summary": "Get pharmacy locations",
      "tag": "Pharmacy"
    },
    "post": {
      "summary": "Create/perform pharmacy locations",
      "tag": "Pharmacy",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/pharmacy/prescriptions": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions",
      "tag": "Pharmacy",
      "permission": "prescription.create"
    },
    "get": {
      "summary": "Get pharmacy prescriptions",
      "tag": "Pharmacy",
      "permission": "pharmacy.view | prescription.create | nursing.view"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}": {
    "get": {
      "summary": "Get pharmacy prescriptions",
      "tag": "Pharmacy",
      "permission": "pharmacy.view | prescription.create"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/cancel": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions cancel",
      "tag": "Pharmacy",
      "permission": "prescription.create | pharmacy.dispense"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/dispense": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions dispense",
      "tag": "Pharmacy",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/eprescription": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions eprescription",
      "tag": "Pharmacy",
      "permission": "prescription.create"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/eprescription/bundle": {
    "get": {
      "summary": "Get pharmacy prescriptions eprescription bundle",
      "tag": "Pharmacy",
      "permission": "prescription.create | pharmacy.view"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/eprescription/dispense": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions eprescription dispense",
      "tag": "Pharmacy",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/eprescription/preview": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions eprescription preview",
      "tag": "Pharmacy",
      "permission": "prescription.create | pharmacy.dispense"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/receive": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions receive",
      "tag": "Pharmacy",
      "permission": "nursing.record"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/return": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions return",
      "tag": "Pharmacy",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/pharmacy/sales": {
    "post": {
      "summary": "Create/perform pharmacy sales",
      "tag": "Pharmacy",
      "permission": "pharmacy.sell"
    },
    "get": {
      "summary": "Get pharmacy sales",
      "tag": "Pharmacy",
      "permission": "pharmacy.sell | pharmacy.view"
    }
  },
  "/api/v1/pharmacy/sales/{id}": {
    "get": {
      "summary": "Get pharmacy sales",
      "tag": "Pharmacy",
      "permission": "pharmacy.sell | pharmacy.view | billing.view"
    }
  },
  "/api/v1/pharmacy/sales/{id}/mpesa": {
    "post": {
      "summary": "Create/perform pharmacy sales mpesa",
      "tag": "Pharmacy",
      "permission": "pharmacy.sell"
    },
    "get": {
      "summary": "Get pharmacy sales mpesa",
      "tag": "Pharmacy",
      "permission": "pharmacy.sell | billing.view"
    }
  },
  "/api/v1/pharmacy/sales/{id}/return": {
    "post": {
      "summary": "Create/perform pharmacy sales return",
      "tag": "Pharmacy",
      "permission": "pharmacy.sell"
    }
  },
  "/api/v1/pharmacy/stock": {
    "get": {
      "summary": "Get pharmacy stock",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/adjust": {
    "post": {
      "summary": "Create/perform pharmacy stock adjust",
      "tag": "Pharmacy",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/pharmacy/stock/expiring": {
    "get": {
      "summary": "Get pharmacy stock expiring",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/movements": {
    "get": {
      "summary": "Get pharmacy stock movements",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/receive": {
    "post": {
      "summary": "Create/perform pharmacy stock receive",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/summary": {
    "get": {
      "summary": "Get pharmacy stock summary",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/transfer": {
    "post": {
      "summary": "Create/perform pharmacy stock transfer",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/z-report": {
    "get": {
      "summary": "Get pharmacy z report",
      "tag": "Pharmacy",
      "permission": "pharmacy.sell | pharmacy.view | billing.view"
    }
  },
  "/api/v1/procurement/purchase-orders": {
    "get": {
      "summary": "Get procurement purchase orders",
      "tag": "Procurement",
      "permission": "procurement.view | inventory.view"
    },
    "post": {
      "summary": "Create/perform procurement purchase orders",
      "tag": "Procurement",
      "permission": "procurement.manage | inventory.manage | pharmacy.stock | lab.manage"
    }
  },
  "/api/v1/procurement/purchase-orders/{id}": {
    "get": {
      "summary": "Get procurement purchase orders",
      "tag": "Procurement",
      "permission": "procurement.view | inventory.view"
    }
  },
  "/api/v1/procurement/purchase-orders/{id}/approve": {
    "post": {
      "summary": "Create/perform procurement purchase orders approve",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/procurement/purchase-orders/{id}/cancel": {
    "post": {
      "summary": "Create/perform procurement purchase orders cancel",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/procurement/purchase-orders/{id}/receive": {
    "post": {
      "summary": "Create/perform procurement purchase orders receive",
      "tag": "Procurement",
      "permission": "procurement.manage | inventory.manage | pharmacy.stock"
    }
  },
  "/api/v1/procurement/suppliers": {
    "get": {
      "summary": "Get procurement suppliers",
      "tag": "Procurement",
      "permission": "procurement.view | inventory.view | pharmacy.stock"
    },
    "post": {
      "summary": "Create/perform procurement suppliers",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/procurement/suppliers/{id}": {
    "patch": {
      "summary": "Update procurement suppliers",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/queues": {
    "get": {
      "summary": "Get queues",
      "tag": "Queues"
    }
  },
  "/api/v1/radiology/exams": {
    "get": {
      "summary": "Get radiology exams",
      "tag": "Radiology",
      "permission": "radiology.view | radiology.order"
    },
    "post": {
      "summary": "Create/perform radiology exams",
      "tag": "Radiology",
      "permission": "radiology.manage"
    }
  },
  "/api/v1/radiology/exams/{code}": {
    "patch": {
      "summary": "Update radiology exams",
      "tag": "Radiology",
      "permission": "radiology.manage"
    }
  },
  "/api/v1/radiology/requests": {
    "post": {
      "summary": "Create/perform radiology requests",
      "tag": "Radiology",
      "permission": "radiology.order"
    },
    "get": {
      "summary": "Get radiology requests",
      "tag": "Radiology",
      "permission": "radiology.view | radiology.order"
    }
  },
  "/api/v1/radiology/requests/{id}": {
    "get": {
      "summary": "Get radiology requests",
      "tag": "Radiology",
      "permission": "radiology.view | radiology.order"
    }
  },
  "/api/v1/radiology/requests/{id}/{step}": {
    "post": {
      "summary": "Create/perform radiology requests",
      "tag": "Radiology"
    }
  },
  "/api/v1/radiology/worklist": {
    "get": {
      "summary": "Get radiology worklist",
      "tag": "Radiology",
      "permission": "radiology.view | radiology.manage"
    }
  },
  "/api/v1/referrals": {
    "post": {
      "summary": "Create/perform referrals",
      "tag": "Referrals",
      "permission": "consultation.create | queue.manage"
    },
    "get": {
      "summary": "Get referrals",
      "tag": "Referrals",
      "permission": "consultation.view | queue.view"
    }
  },
  "/api/v1/referrals/{id}/status": {
    "post": {
      "summary": "Create/perform referrals status",
      "tag": "Referrals",
      "permission": "consultation.create | queue.manage"
    }
  },
  "/api/v1/reports": {
    "get": {
      "summary": "Get reports",
      "tag": "Reports",
      "permission": "reports.view"
    }
  },
  "/api/v1/reports/{key}": {
    "get": {
      "summary": "Get reports",
      "tag": "Reports",
      "permission": "reports.view"
    }
  },
  "/api/v1/roles": {
    "get": {
      "summary": "Get roles",
      "tag": "Roles"
    },
    "post": {
      "summary": "Create/perform roles",
      "tag": "Roles",
      "permission": "admin.roles"
    }
  },
  "/api/v1/roles/{id}": {
    "patch": {
      "summary": "Update roles",
      "tag": "Roles",
      "permission": "admin.roles"
    },
    "delete": {
      "summary": "Delete roles",
      "tag": "Roles",
      "permission": "admin.roles"
    }
  },
  "/api/v1/sha/benefits": {
    "get": {
      "summary": "Get sha benefits",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/biometrics/enrollment-status": {
    "get": {
      "summary": "Get sha biometrics enrollment status",
      "tag": "SHA",
      "permission": "sha.view | sha.authorization"
    }
  },
  "/api/v1/sha/biometrics/enrollments": {
    "post": {
      "summary": "Create/perform sha biometrics enrollments",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/biometrics/jobs": {
    "get": {
      "summary": "Get sha biometrics jobs",
      "tag": "SHA",
      "permission": "sha.view | sha.authorization"
    }
  },
  "/api/v1/sha/biometrics/jobs/{id}": {
    "get": {
      "summary": "Get sha biometrics jobs",
      "tag": "SHA",
      "permission": "sha.view | sha.authorization"
    }
  },
  "/api/v1/sha/biometrics/jobs/{id}/reconcile": {
    "post": {
      "summary": "Create/perform sha biometrics jobs reconcile",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/biometrics/verifications": {
    "post": {
      "summary": "Create/perform sha biometrics verifications",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/callback-endpoints": {
    "get": {
      "summary": "Get sha callback endpoints",
      "tag": "SHA",
      "permission": "admin.integrations"
    },
    "post": {
      "summary": "Create/perform sha callback endpoints",
      "tag": "SHA",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/sha/callback-events": {
    "get": {
      "summary": "Get sha callback events",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/connection": {
    "get": {
      "summary": "Get sha connection",
      "tag": "SHA",
      "permission": "sha.view | admin.integrations"
    }
  },
  "/api/v1/sha/connection/test": {
    "post": {
      "summary": "Create/perform sha connection test",
      "tag": "SHA",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/sha/eligibility": {
    "post": {
      "summary": "Create/perform sha eligibility",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/eligibility/history": {
    "get": {
      "summary": "Get sha eligibility history",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/emergency/doctors": {
    "get": {
      "summary": "Get sha emergency doctors",
      "tag": "SHA",
      "permission": "sha.claim"
    }
  },
  "/api/v1/sha/emergency/protocols": {
    "get": {
      "summary": "Get sha emergency protocols",
      "tag": "SHA",
      "permission": "sha.claim"
    }
  },
  "/api/v1/sha/facility/beds-occupancy": {
    "get": {
      "summary": "Get sha facility beds occupancy",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/hie-callbacks": {
    "get": {
      "summary": "Get sha hie callbacks",
      "tag": "SHA",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/sha/hie-callbacks/active": {
    "post": {
      "summary": "Create/perform sha hie callbacks active",
      "tag": "SHA",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/sha/hie-callbacks/register": {
    "post": {
      "summary": "Create/perform sha hie callbacks register",
      "tag": "SHA",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/sha/interventions": {
    "get": {
      "summary": "Get sha interventions",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/otp-whitelists": {
    "get": {
      "summary": "Get sha otp whitelists",
      "tag": "SHA",
      "permission": "sha.view | sha.authorization"
    },
    "post": {
      "summary": "Create/perform sha otp whitelists",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/pomsf-balances": {
    "get": {
      "summary": "Get sha pomsf balances",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/status": {
    "get": {
      "summary": "Get sha status",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/sub-benefits": {
    "get": {
      "summary": "Get sha sub benefits",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/transactions": {
    "get": {
      "summary": "Get sha transactions",
      "tag": "SHA",
      "permission": "sha.view"
    },
    "post": {
      "summary": "Create/perform sha transactions",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}": {
    "patch": {
      "summary": "Update sha transactions",
      "tag": "SHA"
    },
    "get": {
      "summary": "Get sha transactions",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/transactions/{id}/attachments": {
    "post": {
      "summary": "Create/perform sha transactions attachments",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/cancel": {
    "post": {
      "summary": "Create/perform sha transactions cancel",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/decision": {
    "post": {
      "summary": "Create/perform sha transactions decision",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/emergency/doctors": {
    "post": {
      "summary": "Create/perform sha transactions emergency doctors",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/emergency/doctors/{reg}": {
    "delete": {
      "summary": "Delete sha transactions emergency doctors",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/emergency/protocols": {
    "post": {
      "summary": "Create/perform sha transactions emergency protocols",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/fhir": {
    "get": {
      "summary": "Get sha transactions fhir",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/transactions/{id}/intervention-response": {
    "post": {
      "summary": "Create/perform sha transactions intervention response",
      "tag": "SHA",
      "permission": "sha.intervention"
    }
  },
  "/api/v1/sha/transactions/{id}/reconcile": {
    "post": {
      "summary": "Create/perform sha transactions reconcile",
      "tag": "SHA",
      "permission": "sha.reconciliation"
    }
  },
  "/api/v1/sha/transactions/{id}/resubmit": {
    "post": {
      "summary": "Create/perform sha transactions resubmit",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/submit": {
    "post": {
      "summary": "Create/perform sha transactions submit",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/from-invoice": {
    "post": {
      "summary": "Create/perform sha transactions from invoice",
      "tag": "SHA",
      "permission": "sha.claim"
    }
  },
  "/api/v1/sha/utilization": {
    "get": {
      "summary": "Get sha utilization",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/visits": {
    "get": {
      "summary": "Get sha visits",
      "tag": "SHA",
      "permission": "sha.view"
    },
    "post": {
      "summary": "Create/perform sha visits",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/visits/{id}": {
    "get": {
      "summary": "Get sha visits",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/visits/{id}/authorization/refresh": {
    "post": {
      "summary": "Create/perform sha visits authorization refresh",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/visits/{id}/authorization/reject": {
    "post": {
      "summary": "Create/perform sha visits authorization reject",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/visits/{id}/authorize": {
    "post": {
      "summary": "Create/perform sha visits authorize",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/visits/{id}/claim-steps/{step}": {
    "post": {
      "summary": "Create/perform sha visits claim steps",
      "tag": "SHA",
      "permission": "sha.claim"
    }
  },
  "/api/v1/sha/visits/{id}/contacts": {
    "get": {
      "summary": "Get sha visits contacts",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/visits/{id}/discharge-otp": {
    "post": {
      "summary": "Create/perform sha visits discharge otp",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/visits/{id}/effective-coverage": {
    "post": {
      "summary": "Create/perform sha visits effective coverage",
      "tag": "SHA",
      "permission": "sha.claim"
    }
  },
  "/api/v1/sha/visits/{id}/interventions/{op}": {
    "post": {
      "summary": "Create/perform sha visits interventions",
      "tag": "SHA",
      "permission": "sha.claim"
    }
  },
  "/api/v1/sha/visits/{id}/link-claim": {
    "post": {
      "summary": "Create/perform sha visits link claim",
      "tag": "SHA",
      "permission": "sha.claim"
    }
  },
  "/api/v1/sha/visits/{id}/minor-match": {
    "post": {
      "summary": "Create/perform sha visits minor match",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/visits/{id}/otp": {
    "post": {
      "summary": "Create/perform sha visits otp",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/visits/{id}/preauths": {
    "post": {
      "summary": "Create/perform sha visits preauths",
      "tag": "SHA",
      "permission": "sha.preauthorization"
    }
  },
  "/api/v1/sha/visits/{id}/preauths/{code}": {
    "get": {
      "summary": "Get sha visits preauths",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/visits/{id}/preauths/{code}/{what}": {
    "delete": {
      "summary": "Delete sha visits preauths",
      "tag": "SHA",
      "permission": "sha.preauthorization"
    }
  },
  "/api/v1/sha/visits/{id}/preauths/{code}/cancel": {
    "post": {
      "summary": "Create/perform sha visits preauths cancel",
      "tag": "SHA",
      "permission": "sha.preauthorization"
    }
  },
  "/api/v1/sha/visits/{id}/start": {
    "post": {
      "summary": "Create/perform sha visits start",
      "tag": "SHA",
      "permission": "sha.authorization"
    }
  },
  "/api/v1/sha/workflow": {
    "post": {
      "summary": "Create/perform sha workflow",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sms-wallet": {
    "get": {
      "summary": "Get sms wallet",
      "tag": "Sms wallet"
    }
  },
  "/api/v1/sms-wallet/ledger": {
    "get": {
      "summary": "Get sms wallet ledger",
      "tag": "Sms wallet"
    }
  },
  "/api/v1/sms-wallet/topup": {
    "post": {
      "summary": "Create/perform sms wallet topup",
      "tag": "Sms wallet"
    }
  },
  "/api/v1/sms-wallet/topup/{id}": {
    "get": {
      "summary": "Get sms wallet topup",
      "tag": "Sms wallet"
    }
  },
  "/api/v1/sms/campaigns": {
    "post": {
      "summary": "Create/perform sms campaigns",
      "tag": "Sms"
    },
    "get": {
      "summary": "Get sms campaigns",
      "tag": "Sms"
    }
  },
  "/api/v1/sms/campaigns/{id}": {
    "get": {
      "summary": "Get sms campaigns",
      "tag": "Sms"
    }
  },
  "/api/v1/sms/campaigns/{id}/cancel": {
    "post": {
      "summary": "Create/perform sms campaigns cancel",
      "tag": "Sms"
    }
  },
  "/api/v1/sms/campaigns/preview": {
    "post": {
      "summary": "Create/perform sms campaigns preview",
      "tag": "Sms"
    }
  },
  "/api/v1/subscription": {
    "get": {
      "summary": "Get subscription",
      "tag": "Subscription"
    }
  },
  "/api/v1/subscription/documents": {
    "get": {
      "summary": "Get subscription documents",
      "tag": "Subscription"
    }
  },
  "/api/v1/subscription/documents/{id}": {
    "get": {
      "summary": "Get subscription documents",
      "tag": "Subscription"
    }
  },
  "/api/v1/subscription/documents/{id}/accept": {
    "post": {
      "summary": "Create/perform subscription documents accept",
      "tag": "Subscription"
    }
  },
  "/api/v1/subscription/documents/{id}/decline": {
    "post": {
      "summary": "Create/perform subscription documents decline",
      "tag": "Subscription"
    }
  },
  "/api/v1/subscription/documents/{id}/pay": {
    "post": {
      "summary": "Create/perform subscription documents pay",
      "tag": "Subscription"
    }
  },
  "/api/v1/subscription/documents/{id}/pdf": {
    "get": {
      "summary": "Get subscription documents pdf",
      "tag": "Subscription"
    }
  },
  "/api/v1/subscription/payments/{id}": {
    "get": {
      "summary": "Get subscription payments",
      "tag": "Subscription"
    }
  },
  "/api/v1/subscription/quote": {
    "post": {
      "summary": "Create/perform subscription quote",
      "tag": "Subscription"
    }
  },
  "/api/v1/users": {
    "get": {
      "summary": "Get users",
      "tag": "Users",
      "permission": "admin.users"
    },
    "post": {
      "summary": "Create/perform users",
      "tag": "Users",
      "permission": "admin.users"
    }
  },
  "/api/v1/users/{id}": {
    "patch": {
      "summary": "Update users",
      "tag": "Users",
      "permission": "admin.users"
    }
  },
  "/api/v1/users/{id}/mfa/reset": {
    "post": {
      "summary": "Create/perform users mfa reset",
      "tag": "Users",
      "permission": "admin.users"
    }
  },
  "/api/v1/users/{id}/reset-password": {
    "post": {
      "summary": "Create/perform users reset password",
      "tag": "Users",
      "permission": "admin.users"
    }
  },
  "/api/v1/visits": {
    "post": {
      "summary": "Create/perform visits",
      "tag": "Visits",
      "permission": "queue.manage"
    },
    "get": {
      "summary": "Get visits",
      "tag": "Visits",
      "permission": "queue.view | opd.view | consultation.view"
    }
  },
  "/api/v1/visits/{id}": {
    "get": {
      "summary": "Get visits",
      "tag": "Visits",
      "permission": "queue.view | opd.view | consultation.view"
    }
  },
  "/api/v1/visits/{id}/close": {
    "post": {
      "summary": "Create/perform visits close",
      "tag": "Visits",
      "permission": "queue.manage | consultation.create"
    }
  },
  "/api/v1/visits/{id}/route": {
    "post": {
      "summary": "Create/perform visits route",
      "tag": "Visits",
      "permission": "queue.manage | consultation.create | opd.create"
    }
  },
  "/api/v1/visits/emergency": {
    "post": {
      "summary": "Create/perform visits emergency",
      "tag": "Visits",
      "permission": "patients.create | queue.manage"
    }
  }
};
