// GENERATED by scripts/gen-openapi-routes.mjs — do not edit by hand.
import type { RouteDoc } from './openapi';

export const generatedRoutes: Record<string, Record<string, RouteDoc>> = {
  "/api/v1/admin/audit": {
    "get": {
      "summary": "Get admin audit",
      "tag": "Admin",
      "permission": "admin.audit"
    }
  },
  "/api/v1/admin/integrations": {
    "get": {
      "summary": "Get admin integrations",
      "tag": "Admin",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/admin/integrations/{provider}": {
    "put": {
      "summary": "Replace admin integrations",
      "tag": "Admin",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/admin/integrations/{provider}/test": {
    "post": {
      "summary": "Create/perform admin integrations test",
      "tag": "Admin",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/admin/settings": {
    "get": {
      "summary": "Get admin settings",
      "tag": "Admin",
      "permission": "admin.settings"
    }
  },
  "/api/v1/admin/settings/{key}": {
    "put": {
      "summary": "Replace admin settings",
      "tag": "Admin",
      "permission": "admin.settings"
    }
  },
  "/api/v1/admin/support-access": {
    "get": {
      "summary": "Get admin support access",
      "tag": "Admin",
      "permission": "admin.support_access"
    }
  },
  "/api/v1/admin/support-access/{id}/{decision}": {
    "post": {
      "summary": "Create/perform admin support access",
      "tag": "Admin",
      "permission": "admin.support_access"
    }
  },
  "/api/v1/admin/system-health/integrations": {
    "get": {
      "summary": "Get admin system health integrations",
      "tag": "Admin",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/appointments": {
    "get": {
      "summary": "Get appointments",
      "tag": "Appointments",
      "permission": "appointments.view"
    },
    "post": {
      "summary": "Create/perform appointments",
      "tag": "Appointments",
      "permission": "appointments.manage"
    }
  },
  "/api/v1/appointments/{id}": {
    "patch": {
      "summary": "Update appointments",
      "tag": "Appointments",
      "permission": "appointments.manage"
    }
  },
  "/api/v1/appointments/providers": {
    "get": {
      "summary": "Get appointments providers",
      "tag": "Appointments",
      "permission": "appointments.view"
    }
  },
  "/api/v1/auth/change-password": {
    "post": {
      "summary": "Create/perform auth change password",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/forgot-password": {
    "post": {
      "summary": "Create/perform auth forgot password",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/login": {
    "post": {
      "summary": "Create/perform auth login",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/logout": {
    "post": {
      "summary": "Create/perform auth logout",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/me": {
    "get": {
      "summary": "Get auth me",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/refresh": {
    "post": {
      "summary": "Create/perform auth refresh",
      "tag": "Auth"
    }
  },
  "/api/v1/auth/reset-password": {
    "post": {
      "summary": "Create/perform auth reset password",
      "tag": "Auth"
    }
  },
  "/api/v1/billing/invoices": {
    "get": {
      "summary": "Get billing invoices",
      "tag": "Billing",
      "permission": "billing.view"
    },
    "post": {
      "summary": "Create/perform billing invoices",
      "tag": "Billing",
      "permission": "billing.create"
    }
  },
  "/api/v1/billing/invoices/{id}": {
    "get": {
      "summary": "Get billing invoices",
      "tag": "Billing",
      "permission": "billing.view"
    }
  },
  "/api/v1/billing/invoices/{id}/adjustments": {
    "post": {
      "summary": "Create/perform billing invoices adjustments",
      "tag": "Billing",
      "permission": "billing.waive"
    }
  },
  "/api/v1/billing/invoices/{id}/credit-notes": {
    "post": {
      "summary": "Create/perform billing invoices credit notes",
      "tag": "Billing",
      "permission": "billing.refund"
    }
  },
  "/api/v1/billing/invoices/{id}/issue": {
    "post": {
      "summary": "Create/perform billing invoices issue",
      "tag": "Billing",
      "permission": "billing.create"
    }
  },
  "/api/v1/billing/invoices/{id}/lines": {
    "post": {
      "summary": "Create/perform billing invoices lines",
      "tag": "Billing",
      "permission": "billing.create"
    }
  },
  "/api/v1/billing/invoices/{id}/lines/{lineId}/reprice": {
    "post": {
      "summary": "Create/perform billing invoices lines reprice",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/invoices/{id}/lines/{lineId}/void": {
    "post": {
      "summary": "Create/perform billing invoices lines void",
      "tag": "Billing",
      "permission": "billing.waive"
    }
  },
  "/api/v1/billing/invoices/{id}/void": {
    "post": {
      "summary": "Create/perform billing invoices void",
      "tag": "Billing",
      "permission": "billing.refund"
    }
  },
  "/api/v1/billing/payments": {
    "post": {
      "summary": "Create/perform billing payments",
      "tag": "Billing",
      "permission": "billing.create"
    },
    "get": {
      "summary": "Get billing payments",
      "tag": "Billing",
      "permission": "billing.view"
    }
  },
  "/api/v1/billing/payments/{id}/allocate": {
    "post": {
      "summary": "Create/perform billing payments allocate",
      "tag": "Billing",
      "permission": "billing.create"
    }
  },
  "/api/v1/billing/payments/{id}/receipt": {
    "get": {
      "summary": "Get billing payments receipt",
      "tag": "Billing",
      "permission": "billing.view"
    }
  },
  "/api/v1/billing/payments/{id}/refund": {
    "post": {
      "summary": "Create/perform billing payments refund",
      "tag": "Billing",
      "permission": "billing.refund"
    }
  },
  "/api/v1/billing/services": {
    "get": {
      "summary": "Get billing services",
      "tag": "Billing",
      "permission": "billing.view"
    },
    "post": {
      "summary": "Create/perform billing services",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/services/{id}": {
    "patch": {
      "summary": "Update billing services",
      "tag": "Billing",
      "permission": "billing.prices"
    }
  },
  "/api/v1/billing/summary": {
    "get": {
      "summary": "Get billing summary",
      "tag": "Billing",
      "permission": "billing.view"
    }
  },
  "/api/v1/branches": {
    "get": {
      "summary": "Get branches",
      "tag": "Branches"
    },
    "post": {
      "summary": "Create/perform branches",
      "tag": "Branches",
      "permission": "admin.branches"
    }
  },
  "/api/v1/branches/{id}": {
    "get": {
      "summary": "Get branches",
      "tag": "Branches"
    },
    "patch": {
      "summary": "Update branches",
      "tag": "Branches",
      "permission": "admin.branches"
    }
  },
  "/api/v1/branches/{id}/staff": {
    "put": {
      "summary": "Replace branches staff",
      "tag": "Branches",
      "permission": "admin.users"
    }
  },
  "/api/v1/consultations": {
    "post": {
      "summary": "Create/perform consultations",
      "tag": "Consultations",
      "permission": "consultation.create"
    },
    "get": {
      "summary": "Get consultations",
      "tag": "Consultations",
      "permission": "consultation.view"
    }
  },
  "/api/v1/consultations/{id}": {
    "get": {
      "summary": "Get consultations",
      "tag": "Consultations",
      "permission": "consultation.view"
    },
    "patch": {
      "summary": "Update consultations",
      "tag": "Consultations",
      "permission": "consultation.create"
    }
  },
  "/api/v1/consultations/{id}/addenda": {
    "post": {
      "summary": "Create/perform consultations addenda",
      "tag": "Consultations",
      "permission": "consultation.create"
    }
  },
  "/api/v1/consultations/{id}/finalize": {
    "post": {
      "summary": "Create/perform consultations finalize",
      "tag": "Consultations",
      "permission": "consultation.finalize"
    }
  },
  "/api/v1/dashboard": {
    "get": {
      "summary": "Get dashboard",
      "tag": "Dashboard"
    }
  },
  "/api/v1/dental/patients/{id}/chart": {
    "get": {
      "summary": "Get dental patients chart",
      "tag": "Dental",
      "permission": "dental.view"
    },
    "put": {
      "summary": "Replace dental patients chart",
      "tag": "Dental",
      "permission": "dental.manage"
    }
  },
  "/api/v1/dental/visits": {
    "post": {
      "summary": "Create/perform dental visits",
      "tag": "Dental",
      "permission": "dental.manage"
    }
  },
  "/api/v1/dental/visits/{id}/plan/{itemId}/{action}": {
    "post": {
      "summary": "Create/perform dental visits plan",
      "tag": "Dental",
      "permission": "dental.manage"
    }
  },
  "/api/v1/dha/identification-types": {
    "get": {
      "summary": "Get dha identification types",
      "tag": "DHA",
      "permission": "dha.registry"
    }
  },
  "/api/v1/dha/registries/facilities": {
    "get": {
      "summary": "Get dha registries facilities",
      "tag": "DHA",
      "permission": "dha.registry"
    }
  },
  "/api/v1/dha/registries/practitioners": {
    "get": {
      "summary": "Get dha registries practitioners",
      "tag": "DHA",
      "permission": "dha.registry"
    }
  },
  "/api/v1/dha/status": {
    "get": {
      "summary": "Get dha status",
      "tag": "DHA",
      "permission": "dha.view"
    }
  },
  "/api/v1/documents": {
    "post": {
      "summary": "Create/perform documents",
      "tag": "Documents",
      "permission": "documents.upload"
    },
    "get": {
      "summary": "Get documents",
      "tag": "Documents",
      "permission": "documents.view"
    }
  },
  "/api/v1/documents/{id}/delete": {
    "post": {
      "summary": "Create/perform documents delete",
      "tag": "Documents",
      "permission": "documents.upload"
    }
  },
  "/api/v1/documents/{id}/download": {
    "get": {
      "summary": "Get documents download",
      "tag": "Documents",
      "permission": "documents.view"
    }
  },
  "/api/v1/family-planning/defaulters": {
    "get": {
      "summary": "Get family planning defaulters",
      "tag": "Family planning",
      "permission": "fp.view"
    }
  },
  "/api/v1/family-planning/visits": {
    "post": {
      "summary": "Create/perform family planning visits",
      "tag": "Family planning",
      "permission": "fp.manage"
    },
    "get": {
      "summary": "Get family planning visits",
      "tag": "Family planning",
      "permission": "fp.view"
    }
  },
  "/api/v1/fhir/Encounter/{id}": {
    "get": {
      "summary": "Get fhir Encounter",
      "tag": "FHIR",
      "permission": "consultation.view | dha.fhir"
    }
  },
  "/api/v1/fhir/Location": {
    "get": {
      "summary": "Get fhir Location",
      "tag": "FHIR",
      "permission": "dha.fhir | admin.settings"
    }
  },
  "/api/v1/fhir/metadata": {
    "get": {
      "summary": "Get fhir metadata",
      "tag": "FHIR"
    }
  },
  "/api/v1/fhir/Organization": {
    "get": {
      "summary": "Get fhir Organization",
      "tag": "FHIR",
      "permission": "dha.fhir | admin.settings"
    }
  },
  "/api/v1/fhir/outbox": {
    "get": {
      "summary": "Get fhir outbox",
      "tag": "FHIR",
      "permission": "dha.fhir"
    }
  },
  "/api/v1/fhir/outbox/{id}": {
    "get": {
      "summary": "Get fhir outbox",
      "tag": "FHIR",
      "permission": "dha.fhir"
    }
  },
  "/api/v1/fhir/outbox/{id}/retry": {
    "post": {
      "summary": "Create/perform fhir outbox retry",
      "tag": "FHIR",
      "permission": "dha.fhir"
    }
  },
  "/api/v1/fhir/Patient/{id}": {
    "get": {
      "summary": "Get fhir Patient",
      "tag": "FHIR",
      "permission": "patients.view | dha.fhir"
    }
  },
  "/api/v1/fhir/Patient/{id}/$everything": {
    "get": {
      "summary": "Get fhir Patient everything",
      "tag": "FHIR",
      "permission": "patients.view | consultation.view | dha.fhir"
    }
  },
  "/api/v1/fhir/Practitioner/{id}": {
    "get": {
      "summary": "Get fhir Practitioner",
      "tag": "FHIR",
      "permission": "admin.users | dha.fhir | hr.view"
    }
  },
  "/api/v1/finance/expenses": {
    "post": {
      "summary": "Create/perform finance expenses",
      "tag": "Finance",
      "permission": "finance.manage"
    },
    "get": {
      "summary": "Get finance expenses",
      "tag": "Finance",
      "permission": "finance.view"
    }
  },
  "/api/v1/finance/expenses/{id}/{decision}": {
    "post": {
      "summary": "Create/perform finance expenses",
      "tag": "Finance",
      "permission": "finance.manage"
    }
  },
  "/api/v1/finance/summary": {
    "get": {
      "summary": "Get finance summary",
      "tag": "Finance",
      "permission": "finance.view | reports.view"
    }
  },
  "/api/v1/hr/leave": {
    "post": {
      "summary": "Create/perform hr leave",
      "tag": "HR"
    },
    "get": {
      "summary": "Get hr leave",
      "tag": "HR",
      "permission": "hr.view"
    }
  },
  "/api/v1/hr/leave/{id}/{decision}": {
    "post": {
      "summary": "Create/perform hr leave",
      "tag": "HR",
      "permission": "hr.manage"
    }
  },
  "/api/v1/hr/shifts": {
    "post": {
      "summary": "Create/perform hr shifts",
      "tag": "HR",
      "permission": "hr.manage"
    },
    "get": {
      "summary": "Get hr shifts",
      "tag": "HR",
      "permission": "hr.view"
    }
  },
  "/api/v1/hr/staff": {
    "get": {
      "summary": "Get hr staff",
      "tag": "HR",
      "permission": "hr.view"
    },
    "post": {
      "summary": "Create/perform hr staff",
      "tag": "HR",
      "permission": "hr.manage"
    }
  },
  "/api/v1/hr/staff/{id}": {
    "patch": {
      "summary": "Update hr staff",
      "tag": "HR",
      "permission": "hr.manage"
    }
  },
  "/api/v1/hr/staff/{id}/verify-registry": {
    "post": {
      "summary": "Create/perform hr staff verify registry",
      "tag": "HR",
      "permission": "hr.manage"
    }
  },
  "/api/v1/hr/staff/license-alerts": {
    "get": {
      "summary": "Get hr staff license alerts",
      "tag": "HR",
      "permission": "hr.view"
    }
  },
  "/api/v1/inpatient/admissions": {
    "post": {
      "summary": "Create/perform inpatient admissions",
      "tag": "Inpatient",
      "permission": "inpatient.admit"
    },
    "get": {
      "summary": "Get inpatient admissions",
      "tag": "Inpatient",
      "permission": "inpatient.view | nursing.view"
    }
  },
  "/api/v1/inpatient/admissions/{id}": {
    "get": {
      "summary": "Get inpatient admissions",
      "tag": "Inpatient",
      "permission": "inpatient.view | nursing.view"
    }
  },
  "/api/v1/inpatient/admissions/{id}/discharge": {
    "post": {
      "summary": "Create/perform inpatient admissions discharge",
      "tag": "Inpatient",
      "permission": "inpatient.discharge"
    }
  },
  "/api/v1/inpatient/admissions/{id}/fluids": {
    "post": {
      "summary": "Create/perform inpatient admissions fluids",
      "tag": "Inpatient",
      "permission": "nursing.record"
    }
  },
  "/api/v1/inpatient/admissions/{id}/mar": {
    "post": {
      "summary": "Create/perform inpatient admissions mar",
      "tag": "Inpatient",
      "permission": "nursing.record"
    }
  },
  "/api/v1/inpatient/admissions/{id}/notes": {
    "post": {
      "summary": "Create/perform inpatient admissions notes",
      "tag": "Inpatient",
      "permission": "nursing.record | consultation.create"
    }
  },
  "/api/v1/inpatient/admissions/{id}/transfer": {
    "post": {
      "summary": "Create/perform inpatient admissions transfer",
      "tag": "Inpatient",
      "permission": "inpatient.transfer"
    }
  },
  "/api/v1/inpatient/beds": {
    "get": {
      "summary": "Get inpatient beds",
      "tag": "Inpatient",
      "permission": "inpatient.view | inpatient.manage | nursing.view"
    }
  },
  "/api/v1/inpatient/beds/{id}/status": {
    "post": {
      "summary": "Create/perform inpatient beds status",
      "tag": "Inpatient",
      "permission": "inpatient.manage | nursing.record"
    }
  },
  "/api/v1/inpatient/occupancy": {
    "get": {
      "summary": "Get inpatient occupancy",
      "tag": "Inpatient",
      "permission": "inpatient.view | reports.view | sha.view"
    }
  },
  "/api/v1/inpatient/wards": {
    "get": {
      "summary": "Get inpatient wards",
      "tag": "Inpatient",
      "permission": "inpatient.view | inpatient.manage | nursing.view"
    },
    "post": {
      "summary": "Create/perform inpatient wards",
      "tag": "Inpatient",
      "permission": "inpatient.manage"
    }
  },
  "/api/v1/inpatient/wards/{id}": {
    "patch": {
      "summary": "Update inpatient wards",
      "tag": "Inpatient",
      "permission": "inpatient.manage"
    }
  },
  "/api/v1/inpatient/wards/{id}/beds": {
    "post": {
      "summary": "Create/perform inpatient wards beds",
      "tag": "Inpatient",
      "permission": "inpatient.manage"
    }
  },
  "/api/v1/inventory/items": {
    "get": {
      "summary": "Get inventory items",
      "tag": "Inventory",
      "permission": "prescription.create"
    },
    "post": {
      "summary": "Create/perform inventory items",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/items/{id}": {
    "patch": {
      "summary": "Update inventory items",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/locations": {
    "get": {
      "summary": "Get inventory locations",
      "tag": "Inventory"
    },
    "post": {
      "summary": "Create/perform inventory locations",
      "tag": "Inventory",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/inventory/prescriptions": {
    "post": {
      "summary": "Create/perform inventory prescriptions",
      "tag": "Inventory",
      "permission": "prescription.create"
    },
    "get": {
      "summary": "Get inventory prescriptions",
      "tag": "Inventory",
      "permission": "pharmacy.view | prescription.create | nursing.view"
    }
  },
  "/api/v1/inventory/prescriptions/{id}": {
    "get": {
      "summary": "Get inventory prescriptions",
      "tag": "Inventory",
      "permission": "pharmacy.view | prescription.create"
    }
  },
  "/api/v1/inventory/prescriptions/{id}/cancel": {
    "post": {
      "summary": "Create/perform inventory prescriptions cancel",
      "tag": "Inventory",
      "permission": "prescription.create | pharmacy.dispense"
    }
  },
  "/api/v1/inventory/prescriptions/{id}/dispense": {
    "post": {
      "summary": "Create/perform inventory prescriptions dispense",
      "tag": "Inventory",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/inventory/prescriptions/{id}/return": {
    "post": {
      "summary": "Create/perform inventory prescriptions return",
      "tag": "Inventory",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/inventory/stock": {
    "get": {
      "summary": "Get inventory stock",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/adjust": {
    "post": {
      "summary": "Create/perform inventory stock adjust",
      "tag": "Inventory",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/inventory/stock/expiring": {
    "get": {
      "summary": "Get inventory stock expiring",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/movements": {
    "get": {
      "summary": "Get inventory stock movements",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/receive": {
    "post": {
      "summary": "Create/perform inventory stock receive",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/summary": {
    "get": {
      "summary": "Get inventory stock summary",
      "tag": "Inventory"
    }
  },
  "/api/v1/inventory/stock/transfer": {
    "post": {
      "summary": "Create/perform inventory stock transfer",
      "tag": "Inventory"
    }
  },
  "/api/v1/laboratory/accession/{accession}": {
    "get": {
      "summary": "Get laboratory accession",
      "tag": "Laboratory",
      "permission": "lab.view"
    }
  },
  "/api/v1/laboratory/orders": {
    "post": {
      "summary": "Create/perform laboratory orders",
      "tag": "Laboratory",
      "permission": "lab.order"
    },
    "get": {
      "summary": "Get laboratory orders",
      "tag": "Laboratory",
      "permission": "lab.view"
    }
  },
  "/api/v1/laboratory/orders/{id}": {
    "get": {
      "summary": "Get laboratory orders",
      "tag": "Laboratory",
      "permission": "lab.view"
    }
  },
  "/api/v1/laboratory/orders/{id}/items/{itemId}/{step}": {
    "post": {
      "summary": "Create/perform laboratory orders items",
      "tag": "Laboratory"
    }
  },
  "/api/v1/laboratory/orders/{id}/report": {
    "get": {
      "summary": "Get laboratory orders report",
      "tag": "Laboratory",
      "permission": "lab.view"
    }
  },
  "/api/v1/laboratory/tests": {
    "get": {
      "summary": "Get laboratory tests",
      "tag": "Laboratory",
      "permission": "lab.view"
    },
    "post": {
      "summary": "Create/perform laboratory tests",
      "tag": "Laboratory",
      "permission": "lab.manage"
    }
  },
  "/api/v1/laboratory/tests/{code}": {
    "patch": {
      "summary": "Update laboratory tests",
      "tag": "Laboratory",
      "permission": "lab.manage"
    }
  },
  "/api/v1/maternity/labour/{id}/partograph": {
    "post": {
      "summary": "Create/perform maternity labour partograph",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/maternity/pnc": {
    "post": {
      "summary": "Create/perform maternity pnc",
      "tag": "Maternity",
      "permission": "maternity.manage | mch.manage"
    }
  },
  "/api/v1/maternity/pregnancies": {
    "post": {
      "summary": "Create/perform maternity pregnancies",
      "tag": "Maternity",
      "permission": "maternity.manage"
    },
    "get": {
      "summary": "Get maternity pregnancies",
      "tag": "Maternity",
      "permission": "maternity.view | mch.view"
    }
  },
  "/api/v1/maternity/pregnancies/{id}": {
    "get": {
      "summary": "Get maternity pregnancies",
      "tag": "Maternity",
      "permission": "maternity.view | mch.view"
    }
  },
  "/api/v1/maternity/pregnancies/{id}/anc": {
    "post": {
      "summary": "Create/perform maternity pregnancies anc",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/maternity/pregnancies/{id}/delivery": {
    "post": {
      "summary": "Create/perform maternity pregnancies delivery",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/maternity/pregnancies/{id}/labour": {
    "post": {
      "summary": "Create/perform maternity pregnancies labour",
      "tag": "Maternity",
      "permission": "maternity.manage"
    }
  },
  "/api/v1/mch/defaulters": {
    "get": {
      "summary": "Get mch defaulters",
      "tag": "MCH",
      "permission": "mch.view"
    }
  },
  "/api/v1/mch/growth": {
    "post": {
      "summary": "Create/perform mch growth",
      "tag": "MCH",
      "permission": "mch.manage"
    }
  },
  "/api/v1/mch/immunizations": {
    "post": {
      "summary": "Create/perform mch immunizations",
      "tag": "MCH",
      "permission": "mch.manage"
    }
  },
  "/api/v1/mch/patients/{id}/growth": {
    "get": {
      "summary": "Get mch patients growth",
      "tag": "MCH",
      "permission": "mch.view | maternity.view"
    }
  },
  "/api/v1/mch/patients/{id}/immunizations": {
    "get": {
      "summary": "Get mch patients immunizations",
      "tag": "MCH",
      "permission": "mch.view | maternity.view"
    }
  },
  "/api/v1/mortuary/cases": {
    "post": {
      "summary": "Create/perform mortuary cases",
      "tag": "Mortuary",
      "permission": "mortuary.manage"
    },
    "get": {
      "summary": "Get mortuary cases",
      "tag": "Mortuary",
      "permission": "mortuary.view"
    }
  },
  "/api/v1/mortuary/cases/{id}": {
    "get": {
      "summary": "Get mortuary cases",
      "tag": "Mortuary",
      "permission": "mortuary.view"
    },
    "patch": {
      "summary": "Update mortuary cases",
      "tag": "Mortuary",
      "permission": "mortuary.manage"
    }
  },
  "/api/v1/mortuary/cases/{id}/authorize-release": {
    "post": {
      "summary": "Create/perform mortuary cases authorize release",
      "tag": "Mortuary",
      "permission": "mortuary.release"
    }
  },
  "/api/v1/mortuary/cases/{id}/release": {
    "post": {
      "summary": "Create/perform mortuary cases release",
      "tag": "Mortuary",
      "permission": "mortuary.manage"
    }
  },
  "/api/v1/notifications": {
    "get": {
      "summary": "Get notifications",
      "tag": "Notifications"
    }
  },
  "/api/v1/notifications/{id}/read": {
    "post": {
      "summary": "Create/perform notifications read",
      "tag": "Notifications"
    }
  },
  "/api/v1/notifications/read-all": {
    "post": {
      "summary": "Create/perform notifications read all",
      "tag": "Notifications"
    }
  },
  "/api/v1/opd/diagnoses/search": {
    "get": {
      "summary": "Get opd diagnoses search",
      "tag": "OPD",
      "permission": "consultation.create | consultation.view"
    }
  },
  "/api/v1/opd/patients/{patientId}/summary": {
    "get": {
      "summary": "Get opd patients summary",
      "tag": "OPD",
      "permission": "consultation.view | opd.view | nursing.view"
    }
  },
  "/api/v1/opd/procedures": {
    "post": {
      "summary": "Create/perform opd procedures",
      "tag": "OPD",
      "permission": "consultation.create | nursing.record | dental.manage"
    }
  },
  "/api/v1/opd/procedures/{id}/{action}": {
    "post": {
      "summary": "Create/perform opd procedures",
      "tag": "OPD",
      "permission": "consultation.create | nursing.record | dental.manage"
    }
  },
  "/api/v1/opd/vitals": {
    "post": {
      "summary": "Create/perform opd vitals",
      "tag": "OPD",
      "permission": "opd.create | nursing.record"
    },
    "get": {
      "summary": "Get opd vitals",
      "tag": "OPD",
      "permission": "opd.view | nursing.view | consultation.view"
    }
  },
  "/api/v1/owner/audit": {
    "get": {
      "summary": "Get owner audit",
      "tag": "Owner",
      "permission": "owner.logs"
    }
  },
  "/api/v1/owner/auth/change-password": {
    "post": {
      "summary": "Create/perform owner auth change password",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/auth/login": {
    "post": {
      "summary": "Create/perform owner auth login",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/auth/logout": {
    "post": {
      "summary": "Create/perform owner auth logout",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/auth/me": {
    "get": {
      "summary": "Get owner auth me",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/auth/refresh": {
    "post": {
      "summary": "Create/perform owner auth refresh",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/backups": {
    "get": {
      "summary": "Get owner backups",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/owner/contracts/{provider}": {
    "get": {
      "summary": "Get owner contracts",
      "tag": "Owner",
      "permission": "owner.integrations"
    },
    "patch": {
      "summary": "Update owner contracts",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/dashboard": {
    "get": {
      "summary": "Get owner dashboard",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/integration-logs": {
    "get": {
      "summary": "Get owner integration logs",
      "tag": "Owner",
      "permission": "owner.logs"
    }
  },
  "/api/v1/owner/integrations": {
    "get": {
      "summary": "Get owner integrations",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/integrations/{provider}": {
    "put": {
      "summary": "Replace owner integrations",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/integrations/{provider}/test": {
    "post": {
      "summary": "Create/perform owner integrations test",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/jobs": {
    "get": {
      "summary": "Get owner jobs",
      "tag": "Owner",
      "permission": "owner.logs"
    }
  },
  "/api/v1/owner/jobs/{id}/retry": {
    "post": {
      "summary": "Create/perform owner jobs retry",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/support-access": {
    "post": {
      "summary": "Create/perform owner support access",
      "tag": "Owner",
      "permission": "owner.support"
    },
    "get": {
      "summary": "Get owner support access",
      "tag": "Owner",
      "permission": "owner.support"
    }
  },
  "/api/v1/owner/support-access/{id}/session": {
    "post": {
      "summary": "Create/perform owner support access session",
      "tag": "Owner",
      "permission": "owner.support"
    }
  },
  "/api/v1/owner/system/health": {
    "get": {
      "summary": "Get owner system health",
      "tag": "Owner"
    }
  },
  "/api/v1/owner/tenants": {
    "get": {
      "summary": "Get owner tenants",
      "tag": "Owner",
      "permission": "owner.tenants"
    },
    "post": {
      "summary": "Create/perform owner tenants",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}": {
    "get": {
      "summary": "Get owner tenants",
      "tag": "Owner",
      "permission": "owner.tenants"
    },
    "patch": {
      "summary": "Update owner tenants",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/audit": {
    "get": {
      "summary": "Get owner tenants audit",
      "tag": "Owner",
      "permission": "owner.logs"
    }
  },
  "/api/v1/owner/tenants/{id}/branches": {
    "post": {
      "summary": "Create/perform owner tenants branches",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/domains": {
    "post": {
      "summary": "Create/perform owner tenants domains",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/domains/{domainId}": {
    "delete": {
      "summary": "Delete owner tenants domains",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/domains/{domainId}/verify": {
    "post": {
      "summary": "Create/perform owner tenants domains verify",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/health": {
    "get": {
      "summary": "Get owner tenants health",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/integrations": {
    "put": {
      "summary": "Replace owner tenants integrations",
      "tag": "Owner",
      "permission": "owner.integrations"
    }
  },
  "/api/v1/owner/tenants/{id}/reset-admin": {
    "post": {
      "summary": "Create/perform owner tenants reset admin",
      "tag": "Owner",
      "permission": "owner.tenants"
    }
  },
  "/api/v1/owner/tenants/{id}/subscription": {
    "put": {
      "summary": "Replace owner tenants subscription",
      "tag": "Owner",
      "permission": "owner.subscriptions"
    }
  },
  "/api/v1/owner/users": {
    "get": {
      "summary": "Get owner users",
      "tag": "Owner",
      "permission": "owner.platform"
    },
    "post": {
      "summary": "Create/perform owner users",
      "tag": "Owner",
      "permission": "owner.platform"
    }
  },
  "/api/v1/patients": {
    "get": {
      "summary": "Get patients",
      "tag": "Patients",
      "permission": "patients.view"
    },
    "post": {
      "summary": "Create/perform patients",
      "tag": "Patients",
      "permission": "patients.create"
    }
  },
  "/api/v1/patients/{id}": {
    "get": {
      "summary": "Get patients",
      "tag": "Patients",
      "permission": "patients.view"
    },
    "patch": {
      "summary": "Update patients",
      "tag": "Patients",
      "permission": "patients.edit"
    }
  },
  "/api/v1/patients/{id}/timeline": {
    "get": {
      "summary": "Get patients timeline",
      "tag": "Patients",
      "permission": "patients.view"
    }
  },
  "/api/v1/patients/duplicate-check": {
    "post": {
      "summary": "Create/perform patients duplicate check",
      "tag": "Patients",
      "permission": "patients.create | patients.search"
    }
  },
  "/api/v1/patients/import-dha": {
    "post": {
      "summary": "Create/perform patients import dha",
      "tag": "Patients",
      "permission": "patients.create | dha.registry"
    }
  },
  "/api/v1/patients/link-branch": {
    "post": {
      "summary": "Create/perform patients link branch",
      "tag": "Patients",
      "permission": "patients.create"
    }
  },
  "/api/v1/patients/search": {
    "get": {
      "summary": "Get patients search",
      "tag": "Patients",
      "permission": "patients.search"
    }
  },
  "/api/v1/payments/mpesa/{paymentId}/query": {
    "post": {
      "summary": "Create/perform payments mpesa query",
      "tag": "Payments",
      "permission": "billing.create"
    }
  },
  "/api/v1/payments/mpesa/c2b/{token}/confirmation": {
    "post": {
      "summary": "Create/perform payments mpesa c2b confirmation",
      "tag": "Billing",
      "public": true
    }
  },
  "/api/v1/payments/mpesa/c2b/{token}/validation": {
    "post": {
      "summary": "Create/perform payments mpesa c2b validation",
      "tag": "Billing",
      "public": true
    }
  },
  "/api/v1/payments/mpesa/c2b/register": {
    "post": {
      "summary": "Create/perform payments mpesa c2b register",
      "tag": "Payments",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/payments/mpesa/callback/{token}": {
    "post": {
      "summary": "Create/perform payments mpesa callback",
      "tag": "Billing",
      "public": true
    }
  },
  "/api/v1/payments/mpesa/stk": {
    "post": {
      "summary": "Create/perform payments mpesa stk",
      "tag": "Payments",
      "permission": "billing.create"
    }
  },
  "/api/v1/pharmacy/items": {
    "get": {
      "summary": "Get pharmacy items",
      "tag": "Pharmacy",
      "permission": "prescription.create"
    },
    "post": {
      "summary": "Create/perform pharmacy items",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/items/{id}": {
    "patch": {
      "summary": "Update pharmacy items",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/locations": {
    "get": {
      "summary": "Get pharmacy locations",
      "tag": "Pharmacy"
    },
    "post": {
      "summary": "Create/perform pharmacy locations",
      "tag": "Pharmacy",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/pharmacy/prescriptions": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions",
      "tag": "Pharmacy",
      "permission": "prescription.create"
    },
    "get": {
      "summary": "Get pharmacy prescriptions",
      "tag": "Pharmacy",
      "permission": "pharmacy.view | prescription.create | nursing.view"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}": {
    "get": {
      "summary": "Get pharmacy prescriptions",
      "tag": "Pharmacy",
      "permission": "pharmacy.view | prescription.create"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/cancel": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions cancel",
      "tag": "Pharmacy",
      "permission": "prescription.create | pharmacy.dispense"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/dispense": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions dispense",
      "tag": "Pharmacy",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/pharmacy/prescriptions/{id}/return": {
    "post": {
      "summary": "Create/perform pharmacy prescriptions return",
      "tag": "Pharmacy",
      "permission": "pharmacy.dispense"
    }
  },
  "/api/v1/pharmacy/stock": {
    "get": {
      "summary": "Get pharmacy stock",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/adjust": {
    "post": {
      "summary": "Create/perform pharmacy stock adjust",
      "tag": "Pharmacy",
      "permission": "inventory.manage"
    }
  },
  "/api/v1/pharmacy/stock/expiring": {
    "get": {
      "summary": "Get pharmacy stock expiring",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/movements": {
    "get": {
      "summary": "Get pharmacy stock movements",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/receive": {
    "post": {
      "summary": "Create/perform pharmacy stock receive",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/summary": {
    "get": {
      "summary": "Get pharmacy stock summary",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/pharmacy/stock/transfer": {
    "post": {
      "summary": "Create/perform pharmacy stock transfer",
      "tag": "Pharmacy"
    }
  },
  "/api/v1/procurement/purchase-orders": {
    "get": {
      "summary": "Get procurement purchase orders",
      "tag": "Procurement",
      "permission": "procurement.view | inventory.view"
    },
    "post": {
      "summary": "Create/perform procurement purchase orders",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/procurement/purchase-orders/{id}": {
    "get": {
      "summary": "Get procurement purchase orders",
      "tag": "Procurement",
      "permission": "procurement.view | inventory.view"
    }
  },
  "/api/v1/procurement/purchase-orders/{id}/approve": {
    "post": {
      "summary": "Create/perform procurement purchase orders approve",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/procurement/purchase-orders/{id}/cancel": {
    "post": {
      "summary": "Create/perform procurement purchase orders cancel",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/procurement/purchase-orders/{id}/receive": {
    "post": {
      "summary": "Create/perform procurement purchase orders receive",
      "tag": "Procurement",
      "permission": "procurement.manage | inventory.manage | pharmacy.stock"
    }
  },
  "/api/v1/procurement/suppliers": {
    "get": {
      "summary": "Get procurement suppliers",
      "tag": "Procurement",
      "permission": "procurement.view | inventory.view | pharmacy.stock"
    },
    "post": {
      "summary": "Create/perform procurement suppliers",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/procurement/suppliers/{id}": {
    "patch": {
      "summary": "Update procurement suppliers",
      "tag": "Procurement",
      "permission": "procurement.manage"
    }
  },
  "/api/v1/queues": {
    "get": {
      "summary": "Get queues",
      "tag": "Queues"
    }
  },
  "/api/v1/radiology/exams": {
    "get": {
      "summary": "Get radiology exams",
      "tag": "Radiology",
      "permission": "radiology.view | radiology.order"
    },
    "post": {
      "summary": "Create/perform radiology exams",
      "tag": "Radiology",
      "permission": "radiology.manage"
    }
  },
  "/api/v1/radiology/exams/{code}": {
    "patch": {
      "summary": "Update radiology exams",
      "tag": "Radiology",
      "permission": "radiology.manage"
    }
  },
  "/api/v1/radiology/requests": {
    "post": {
      "summary": "Create/perform radiology requests",
      "tag": "Radiology",
      "permission": "radiology.order"
    },
    "get": {
      "summary": "Get radiology requests",
      "tag": "Radiology",
      "permission": "radiology.view | radiology.order"
    }
  },
  "/api/v1/radiology/requests/{id}": {
    "get": {
      "summary": "Get radiology requests",
      "tag": "Radiology",
      "permission": "radiology.view | radiology.order"
    }
  },
  "/api/v1/radiology/requests/{id}/{step}": {
    "post": {
      "summary": "Create/perform radiology requests",
      "tag": "Radiology"
    }
  },
  "/api/v1/radiology/worklist": {
    "get": {
      "summary": "Get radiology worklist",
      "tag": "Radiology",
      "permission": "radiology.view | radiology.manage"
    }
  },
  "/api/v1/referrals": {
    "post": {
      "summary": "Create/perform referrals",
      "tag": "Referrals",
      "permission": "consultation.create | queue.manage"
    },
    "get": {
      "summary": "Get referrals",
      "tag": "Referrals",
      "permission": "consultation.view | queue.view"
    }
  },
  "/api/v1/referrals/{id}/status": {
    "post": {
      "summary": "Create/perform referrals status",
      "tag": "Referrals",
      "permission": "consultation.create | queue.manage"
    }
  },
  "/api/v1/reports": {
    "get": {
      "summary": "Get reports",
      "tag": "Reports",
      "permission": "reports.view"
    }
  },
  "/api/v1/reports/{key}": {
    "get": {
      "summary": "Get reports",
      "tag": "Reports",
      "permission": "reports.view"
    }
  },
  "/api/v1/roles": {
    "get": {
      "summary": "Get roles",
      "tag": "Roles"
    },
    "post": {
      "summary": "Create/perform roles",
      "tag": "Roles",
      "permission": "admin.roles"
    }
  },
  "/api/v1/roles/{id}": {
    "patch": {
      "summary": "Update roles",
      "tag": "Roles",
      "permission": "admin.roles"
    },
    "delete": {
      "summary": "Delete roles",
      "tag": "Roles",
      "permission": "admin.roles"
    }
  },
  "/api/v1/sha/benefits": {
    "get": {
      "summary": "Get sha benefits",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/callback-endpoints": {
    "get": {
      "summary": "Get sha callback endpoints",
      "tag": "SHA",
      "permission": "admin.integrations"
    },
    "post": {
      "summary": "Create/perform sha callback endpoints",
      "tag": "SHA",
      "permission": "admin.integrations"
    }
  },
  "/api/v1/sha/callback-events": {
    "get": {
      "summary": "Get sha callback events",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/eligibility": {
    "post": {
      "summary": "Create/perform sha eligibility",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/eligibility/history": {
    "get": {
      "summary": "Get sha eligibility history",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/facility/beds-occupancy": {
    "get": {
      "summary": "Get sha facility beds occupancy",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/interventions": {
    "get": {
      "summary": "Get sha interventions",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/sha/status": {
    "get": {
      "summary": "Get sha status",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/transactions": {
    "get": {
      "summary": "Get sha transactions",
      "tag": "SHA",
      "permission": "sha.view"
    },
    "post": {
      "summary": "Create/perform sha transactions",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}": {
    "patch": {
      "summary": "Update sha transactions",
      "tag": "SHA"
    },
    "get": {
      "summary": "Get sha transactions",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/transactions/{id}/attachments": {
    "post": {
      "summary": "Create/perform sha transactions attachments",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/cancel": {
    "post": {
      "summary": "Create/perform sha transactions cancel",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/decision": {
    "post": {
      "summary": "Create/perform sha transactions decision",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/fhir": {
    "get": {
      "summary": "Get sha transactions fhir",
      "tag": "SHA",
      "permission": "sha.view"
    }
  },
  "/api/v1/sha/transactions/{id}/intervention-response": {
    "post": {
      "summary": "Create/perform sha transactions intervention response",
      "tag": "SHA",
      "permission": "sha.intervention"
    }
  },
  "/api/v1/sha/transactions/{id}/reconcile": {
    "post": {
      "summary": "Create/perform sha transactions reconcile",
      "tag": "SHA",
      "permission": "sha.reconciliation"
    }
  },
  "/api/v1/sha/transactions/{id}/resubmit": {
    "post": {
      "summary": "Create/perform sha transactions resubmit",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/{id}/submit": {
    "post": {
      "summary": "Create/perform sha transactions submit",
      "tag": "SHA"
    }
  },
  "/api/v1/sha/transactions/from-invoice": {
    "post": {
      "summary": "Create/perform sha transactions from invoice",
      "tag": "SHA",
      "permission": "sha.claim"
    }
  },
  "/api/v1/sha/utilization": {
    "get": {
      "summary": "Get sha utilization",
      "tag": "SHA",
      "permission": "sha.eligibility"
    }
  },
  "/api/v1/users": {
    "get": {
      "summary": "Get users",
      "tag": "Users",
      "permission": "admin.users"
    },
    "post": {
      "summary": "Create/perform users",
      "tag": "Users",
      "permission": "admin.users"
    }
  },
  "/api/v1/users/{id}": {
    "patch": {
      "summary": "Update users",
      "tag": "Users",
      "permission": "admin.users"
    }
  },
  "/api/v1/users/{id}/reset-password": {
    "post": {
      "summary": "Create/perform users reset password",
      "tag": "Users",
      "permission": "admin.users"
    }
  },
  "/api/v1/visits": {
    "post": {
      "summary": "Create/perform visits",
      "tag": "Visits",
      "permission": "queue.manage"
    },
    "get": {
      "summary": "Get visits",
      "tag": "Visits",
      "permission": "queue.view | opd.view | consultation.view"
    }
  },
  "/api/v1/visits/{id}": {
    "get": {
      "summary": "Get visits",
      "tag": "Visits",
      "permission": "queue.view | opd.view | consultation.view"
    }
  },
  "/api/v1/visits/{id}/close": {
    "post": {
      "summary": "Create/perform visits close",
      "tag": "Visits",
      "permission": "queue.manage | consultation.create"
    }
  },
  "/api/v1/visits/{id}/route": {
    "post": {
      "summary": "Create/perform visits route",
      "tag": "Visits",
      "permission": "queue.manage | consultation.create | opd.create"
    }
  },
  "/api/v1/visits/emergency": {
    "post": {
      "summary": "Create/perform visits emergency",
      "tag": "Visits",
      "permission": "patients.create | queue.manage"
    }
  }
};
