#!/usr/bin/env bash
# Regenerates /etc/nginx/cloudflare_realip.conf from Cloudflare's published address list, then reloads nginx.
# Run once after installing, and monthly from cron:  0 4 1 * * /var/www/afeySync/deploy/update-cloudflare-ips.sh
set -euo pipefail
out=/etc/nginx/cloudflare_realip.conf
tmp=$(mktemp)
{
  echo "# Generated by update-cloudflare-ips.sh on $(date -u +%F). Restores the visitor's real IP behind Cloudflare."
  for ip in $(curl -fsS https://www.cloudflare.com/ips-v4) $(curl -fsS https://www.cloudflare.com/ips-v6); do
    echo "set_real_ip_from $ip;"
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$tmp"
grep -q set_real_ip_from "$tmp" || { echo "Could not download the Cloudflare list; keeping the current file." >&2; exit 1; }
cp "$tmp" "$out" && rm -f "$tmp"
nginx -t && systemctl reload nginx
echo "Updated $out"
